/*
 *  Copyright 2015 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets; 1, 0, 1,0; 7-10-2015 12:05:59; /db/ztree/library/trees/xdctargets/xdctargets-j04/src/ xlibrary

 */

