# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/


FILE = vcop_fft_1024_16x16t
TEST_BENCH = $(FILE)_tb
include ../../../common/Makefile.wincommon

