/* ======================================================================
 *   Copyright (C) 2013 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */
/*
 * main_a15.c
 */
#include "stdint.h"
#include "mailbox.h"
#include "soc_defines.h"
#include "uartStdio.h"
#include "stdint.h"
#include "stdio.h"
#include "interrupt.h"
#include "platform.h"
#include "soc.h"
#ifndef TI814X_FAMILY_BUILD
#include "irq_xbar.h"
#endif
#include "mailbox_app.h"

#ifdef TI814X_FAMILY_BUILD
/* Sender will run on M3 and DSP */
#define MAILBOX_IRQ_NO          (77U)
#define IRQ_XABR_CFG_REQUIRED   (0U)
#define MAILBOX_BASE_ADDRESS    SOC_SYSTEM_MAILBOX
#define MAILBOX_USER            (0U)

#elif defined (TDA2XX_FAMILY_BUILD)
/* Sender will run on M4 and DSP */
#ifdef BUILD_M4
#define MAILBOX_IRQ_NO          (50U)
#define IRQ_XBAR_CPU_ID         CPU_IPU1
#define IRQ_XBAR_INST_NO        XBAR_INST_IPU1_IRQ_50
#define IRQ_XBAR_INDEX          MAILBOX2_IRQ_USER2
#define MAILBOX_USER            (2U)
#elif BUILD_DSP
#define MAILBOX_IRQ_NO          (52U)
#define IRQ_XBAR_CPU_ID         CPU_DSP1
#define IRQ_XBAR_INST_NO        XBAR_INST_DSP1_IRQ_52
#define IRQ_XBAR_INDEX          MAILBOX2_IRQ_USER1
#define MAILBOX_USER            (1U)
#endif
#define IRQ_XABR_CFG_REQUIRED   (1U)
#define MAILBOX_BASE_ADDRESS    SOC_MAILBOX2_BASE

#elif defined (TDA3XX_FAMILY_BUILD)
/* Sender will run on DSP */
#define MAILBOX_IRQ_NO          (52U)
#define IRQ_XABR_CFG_REQUIRED   (1U)
#define IRQ_XBAR_CPU_ID         CPU_DSP1
#define IRQ_XBAR_INST_NO        XBAR_INST_DSP1_IRQ_52
#define IRQ_XBAR_INDEX          MAILBOX2_IRQ_USER1
#define MAILBOX_USER            (1U)
#define MAILBOX_BASE_ADDRESS    SOC_MAILBOX2_BASE
#endif

void mailboxisr(void *handle);

int main(void)
{
#if IRQ_XABR_CFG_REQUIRED
    irq_xbar_ret_type_t status = invalid_mpu_id;
#endif

    PlatformUartConsoleSetPinMux();
    UARTStdioInit();

    UARTPuts("\nSender: Mailbox Application ", -1);

#ifdef TI814X_FAMILY_BUILD
    /* For TI814X Directly write to the mailbox */
    MailboxSendMessage(SOC_SYSTEM_MAILBOX, MAILBOX_QUEUE_0,
                       (uint32_t) MAILBOX_APP_MSG_TO_SEND);
#else
#if IRQ_XABR_CFG_REQUIRED
    /*Unlock the Crossbar register */
    PlatformUnlockMMR();

    status =
        IRQXBARConnect(SOC_IRQ_DMARQ_CROSSBAR_REGISTERS_BASE, IRQ_XBAR_CPU_ID,
                       IRQ_XBAR_INST_NO,
                       IRQ_XBAR_INDEX);

    if (status == irq_xbar_success)
    {
        UARTPuts("\nSender:  XBar is sucessfully connected", -1);
    }
    else
    {
        UARTPuts("\nSender:  XBar not able to connect", -1);
    }
#endif

    /* Register Mailbox interrupt for A15 */
    Intc_Init();
    Intc_IntEnable(0);
    Intc_IntRegister(MAILBOX_IRQ_NO, (IntrFuncPtr) mailboxisr, NULL);
    Intc_IntPrioritySet(MAILBOX_IRQ_NO, 1, 0);
    Intc_SystemEnable(MAILBOX_IRQ_NO);

    /* Clear Queue Not Full Interrupt generated by deafult */
    MailboxClrQueueNotFullStatus(MAILBOX_BASE_ADDRESS, MAILBOX_USER,
                                 MAILBOX_QUEUE_0);

    /* Enable Queue Not Full Interrupt */
    MailboxEnableQueueNotFullInt(MAILBOX_BASE_ADDRESS, MAILBOX_USER,
                                 MAILBOX_QUEUE_0);
#endif
    return 0;
}

void mailboxisr(void *handle)
{
    UARTPuts("\nSender: FIFO is not full: Send Message", -1);

    MailboxDisableQueueNotFullInt(MAILBOX_BASE_ADDRESS, MAILBOX_USER,
                                  MAILBOX_QUEUE_0);

    MailboxSendMessage(MAILBOX_BASE_ADDRESS, MAILBOX_QUEUE_0,
                       (uint32_t) MAILBOX_APP_MSG_TO_SEND);
}

