#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/ipc/mm
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/utils.js:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/utils.js
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xdc.tci:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xdc.tci
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/template.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/template.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/om2.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/om2.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xmlgen.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xmlgen.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xmlgen2.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xmlgen2.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/Warnings.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/Warnings.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/IPackage.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/IPackage.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/package.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/package.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/services/global/Clock.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/services/global/Clock.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/services/global/Trace.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/services/global/Trace.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/bld.js:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/bld.js
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/BuildEnvironment.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/PackageContents.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/PackageContents.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/_gen.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/_gen.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Library.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Library.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Executable.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Executable.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Repository.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Repository.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Configuration.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Configuration.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Script.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Script.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Manifest.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Manifest.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Utils.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Utils.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget2.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget2.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget3.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget3.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITargetFilter.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/package.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/package.xs
/datalocal1/ti_components/os_tools/ipc_3_40_00_06/ipc-bios.bld:
package.mak: /datalocal1/ti_components/os_tools/ipc_3_40_00_06/ipc-bios.bld
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/ITarget.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/ITarget.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/C28_large.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/C28_large.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/C28_float.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/C28_float.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/package.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/package.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/IArm.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/package.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/package.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/ITarget.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/ITarget.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/package.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/package.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/IARP32.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/IARP32.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/package.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/package.xs
package.mak: package.bld
endif

ti.targets.arm.elf.M4.rootDir ?= /datalocal1/ti_components/cg_tools/linux/ti-cgt-arm_5.2.5
ti.targets.arm.elf.packageBase ?= /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/
ti.targets.elf.C66.rootDir ?= /datalocal1/ti_components/cg_tools/linux/c6000_7_4_2
ti.targets.elf.packageBase ?= /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/
ti.targets.arp32.elf.ARP32.rootDir ?= /datalocal1/ti_components/cg_tools/linux/arp32_1_0_6
ti.targets.arp32.elf.packageBase ?= /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oem4
.PHONY: all,em4 .dlls,em4 .executables,em4 test,em4
all,em4: .executables,em4
.executables,em4: .libraries,em4
.executables,em4: .dlls,em4
.dlls,em4: .libraries,em4
.libraries,em4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em4
	@$(ECHO) xdc .executables,em4
	@$(ECHO) xdc .libraries,em4
	@$(ECHO) xdc .dlls,em4

.PRECIOUS: $(XDCCFGDIR)/%.oe66
.PHONY: all,e66 .dlls,e66 .executables,e66 test,e66
all,e66: .executables,e66
.executables,e66: .libraries,e66
.executables,e66: .dlls,e66
.dlls,e66: .libraries,e66
.libraries,e66: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e66
	@$(ECHO) xdc .executables,e66
	@$(ECHO) xdc .libraries,e66
	@$(ECHO) xdc .dlls,e66

.PRECIOUS: $(XDCCFGDIR)/%.oearp32
.PHONY: all,earp32 .dlls,earp32 .executables,earp32 test,earp32
all,earp32: .executables,earp32
.executables,earp32: .libraries,earp32
.executables,earp32: .dlls,earp32
.dlls,earp32: .libraries,earp32
.libraries,earp32: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,earp32
	@$(ECHO) xdc .executables,earp32
	@$(ECHO) xdc .libraries,earp32
	@$(ECHO) xdc .dlls,earp32


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.ipc.mm.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.ipc.mm" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.ipc.mm $@

.libraries,em4 .libraries: lib/debug/ti_ipc_mm.aem4

-include lib/debug/ti_ipc_mm.aem4.mak
lib/debug/ti_ipc_mm.aem4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.oem4 package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.oem4  into $@ ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armar  rq $@   package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.oem4 package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.oem4 
lib/debug/ti_ipc_mm.aem4: export C_DIR=
lib/debug/ti_ipc_mm.aem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 clean::
	-$(RM) lib/debug/ti_ipc_mm.aem4
.libraries,em4 .libraries: lib/release/ti_ipc_mm.aem4

-include lib/release/ti_ipc_mm.aem4.mak
lib/release/ti_ipc_mm.aem4: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.oem4 package/lib/lib/release/ti_ipc_mm/MmServiceMgr.oem4  into $@ ...
	$(ti.targets.arm.elf.M4.rootDir)/bin/armar  rq $@   package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.oem4 package/lib/lib/release/ti_ipc_mm/MmServiceMgr.oem4 
lib/release/ti_ipc_mm.aem4: export C_DIR=
lib/release/ti_ipc_mm.aem4: PATH:=$(ti.targets.arm.elf.M4.rootDir)/bin/:$(PATH)

clean,em4 clean::
	-$(RM) lib/release/ti_ipc_mm.aem4
.libraries,e66 .libraries: lib/debug/ti_ipc_mm.ae66

-include lib/debug/ti_ipc_mm.ae66.mak
lib/debug/ti_ipc_mm.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.oe66 package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.oe66 package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.oe66 
lib/debug/ti_ipc_mm.ae66: export C_DIR=
lib/debug/ti_ipc_mm.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/debug/ti_ipc_mm.ae66
.libraries,e66 .libraries: lib/release/ti_ipc_mm.ae66

-include lib/release/ti_ipc_mm.ae66.mak
lib/release/ti_ipc_mm.ae66: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.oe66 package/lib/lib/release/ti_ipc_mm/MmServiceMgr.oe66  into $@ ...
	$(ti.targets.elf.C66.rootDir)/bin/ar6x  rq $@   package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.oe66 package/lib/lib/release/ti_ipc_mm/MmServiceMgr.oe66 
lib/release/ti_ipc_mm.ae66: export C_DIR=
lib/release/ti_ipc_mm.ae66: PATH:=$(ti.targets.elf.C66.rootDir)/bin/:$(PATH)

clean,e66 clean::
	-$(RM) lib/release/ti_ipc_mm.ae66
.libraries,earp32 .libraries: lib/debug/ti_ipc_mm.aearp32

-include lib/debug/ti_ipc_mm.aearp32.mak
lib/debug/ti_ipc_mm.aearp32: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.oearp32 package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.oearp32  into $@ ...
	$(ti.targets.arp32.elf.ARP32.rootDir)/bin/ar-arp32  rq $@   package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.oearp32 package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.oearp32 
lib/debug/ti_ipc_mm.aearp32: export C_DIR=
lib/debug/ti_ipc_mm.aearp32: PATH:=$(ti.targets.arp32.elf.ARP32.rootDir)/bin/:$(PATH)

clean,earp32 clean::
	-$(RM) lib/debug/ti_ipc_mm.aearp32
.libraries,earp32 .libraries: lib/release/ti_ipc_mm.aearp32

-include lib/release/ti_ipc_mm.aearp32.mak
lib/release/ti_ipc_mm.aearp32: 
	$(RM) $@
	@$(MSG) archiving package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.oearp32 package/lib/lib/release/ti_ipc_mm/MmServiceMgr.oearp32  into $@ ...
	$(ti.targets.arp32.elf.ARP32.rootDir)/bin/ar-arp32  rq $@   package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.oearp32 package/lib/lib/release/ti_ipc_mm/MmServiceMgr.oearp32 
lib/release/ti_ipc_mm.aearp32: export C_DIR=
lib/release/ti_ipc_mm.aearp32: PATH:=$(ti.targets.arp32.elf.ARP32.rootDir)/bin/:$(PATH)

clean,earp32 clean::
	-$(RM) lib/release/ti_ipc_mm.aearp32
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
.PHONY: package_ti.ipc.mm.oem4,copy
package_ti.ipc.mm.oem4,copy : package_ti.ipc.mm.oem4,0,copy package_ti.ipc.mm.oem4,1,copy 
	@

package_ti.ipc.mm.oem4,0,copy : package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.oem4
package_ti.ipc.mm.oem4,1,copy : package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.oem4
.PHONY: package_ti.ipc.mm.sem4,copy
package_ti.ipc.mm.sem4,copy : package_ti.ipc.mm.sem4,0,copy package_ti.ipc.mm.sem4,1,copy 
	@

package_ti.ipc.mm.sem4,0,copy : package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.sem4
package_ti.ipc.mm.sem4,1,copy : package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.sem4
.PHONY: MmServiceMgr.oem4,copy
MmServiceMgr.oem4,copy : MmServiceMgr.oem4,0,copy MmServiceMgr.oem4,1,copy 
	@

MmServiceMgr.oem4,0,copy : package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.oem4
MmServiceMgr.oem4,1,copy : package/lib/lib/release/ti_ipc_mm/MmServiceMgr.oem4
.PHONY: MmServiceMgr.sem4,copy
MmServiceMgr.sem4,copy : MmServiceMgr.sem4,0,copy MmServiceMgr.sem4,1,copy 
	@

MmServiceMgr.sem4,0,copy : package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.sem4
MmServiceMgr.sem4,1,copy : package/lib/lib/release/ti_ipc_mm/MmServiceMgr.sem4
.PHONY: package_ti.ipc.mm.oe66,copy
package_ti.ipc.mm.oe66,copy : package_ti.ipc.mm.oe66,0,copy package_ti.ipc.mm.oe66,1,copy 
	@

package_ti.ipc.mm.oe66,0,copy : package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.oe66
package_ti.ipc.mm.oe66,1,copy : package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.oe66
.PHONY: package_ti.ipc.mm.se66,copy
package_ti.ipc.mm.se66,copy : package_ti.ipc.mm.se66,0,copy package_ti.ipc.mm.se66,1,copy 
	@

package_ti.ipc.mm.se66,0,copy : package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.se66
package_ti.ipc.mm.se66,1,copy : package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.se66
.PHONY: MmServiceMgr.oe66,copy
MmServiceMgr.oe66,copy : MmServiceMgr.oe66,0,copy MmServiceMgr.oe66,1,copy 
	@

MmServiceMgr.oe66,0,copy : package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.oe66
MmServiceMgr.oe66,1,copy : package/lib/lib/release/ti_ipc_mm/MmServiceMgr.oe66
.PHONY: MmServiceMgr.se66,copy
MmServiceMgr.se66,copy : MmServiceMgr.se66,0,copy MmServiceMgr.se66,1,copy 
	@

MmServiceMgr.se66,0,copy : package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.se66
MmServiceMgr.se66,1,copy : package/lib/lib/release/ti_ipc_mm/MmServiceMgr.se66
.PHONY: package_ti.ipc.mm.oearp32,copy
package_ti.ipc.mm.oearp32,copy : package_ti.ipc.mm.oearp32,0,copy package_ti.ipc.mm.oearp32,1,copy 
	@

package_ti.ipc.mm.oearp32,0,copy : package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.oearp32
package_ti.ipc.mm.oearp32,1,copy : package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.oearp32
.PHONY: package_ti.ipc.mm.searp32,copy
package_ti.ipc.mm.searp32,copy : package_ti.ipc.mm.searp32,0,copy package_ti.ipc.mm.searp32,1,copy 
	@

package_ti.ipc.mm.searp32,0,copy : package/lib/lib/debug/ti_ipc_mm/package/package_ti.ipc.mm.searp32
package_ti.ipc.mm.searp32,1,copy : package/lib/lib/release/ti_ipc_mm/package/package_ti.ipc.mm.searp32
.PHONY: MmServiceMgr.oearp32,copy
MmServiceMgr.oearp32,copy : MmServiceMgr.oearp32,0,copy MmServiceMgr.oearp32,1,copy 
	@

MmServiceMgr.oearp32,0,copy : package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.oearp32
MmServiceMgr.oearp32,1,copy : package/lib/lib/release/ti_ipc_mm/MmServiceMgr.oearp32
.PHONY: MmServiceMgr.searp32,copy
MmServiceMgr.searp32,copy : MmServiceMgr.searp32,0,copy MmServiceMgr.searp32,1,copy 
	@

MmServiceMgr.searp32,0,copy : package/lib/lib/debug/ti_ipc_mm/MmServiceMgr.searp32
MmServiceMgr.searp32,1,copy : package/lib/lib/release/ti_ipc_mm/MmServiceMgr.searp32

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_ipc_mm
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_ipc_mm.tar.gz.dep
endif
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: package/package.bld.xml
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: package/build.cfg
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: package/package.xdc.inc
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: package.bld
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: MmRpc.h
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: MmRpc.c
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: MmServiceMgr.h
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: MmType.h
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: lib/debug/ti_ipc_mm.aem4
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: package/package_ti.ipc.mm.c
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: MmServiceMgr.c
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: lib/release/ti_ipc_mm.aem4
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: lib/debug/ti_ipc_mm.ae66
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: lib/release/ti_ipc_mm.ae66
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: lib/debug/ti_ipc_mm.aearp32
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: lib/release/ti_ipc_mm.aearp32
package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_ipc_mm.tar.gz: package/rel/ti_ipc_mm.xdc.inc package/rel/ti_ipc_mm/ti/ipc/mm/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_ipc_mm.xdc.inc,package/rel/ti_ipc_mm.tar.gz.dep)


release release,ti_ipc_mm: all ti_ipc_mm.tar.gz
clean:: .clean
	-$(RM) ti_ipc_mm.tar.gz
	-$(RM) package/rel/ti_ipc_mm.xdc.inc
	-$(RM) package/rel/ti_ipc_mm.tar.gz.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/
	-$(RMDIR) lib/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard lib))
    $(shell $(MKDIR) lib)
endif
ifeq (,$(wildcard lib/debug))
    $(shell $(MKDIR) lib/debug)
endif
ifeq (,$(wildcard lib/release))
    $(shell $(MKDIR) lib/release)
endif
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
ifeq (,$(wildcard package/lib/lib))
    $(shell $(MKDIR) package/lib/lib)
endif
ifeq (,$(wildcard package/lib/lib/debug))
    $(shell $(MKDIR) package/lib/lib/debug)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti_ipc_mm))
    $(shell $(MKDIR) package/lib/lib/debug/ti_ipc_mm)
endif
ifeq (,$(wildcard package/lib/lib/debug/ti_ipc_mm/package))
    $(shell $(MKDIR) package/lib/lib/debug/ti_ipc_mm/package)
endif
ifeq (,$(wildcard package/lib/lib/release))
    $(shell $(MKDIR) package/lib/lib/release)
endif
ifeq (,$(wildcard package/lib/lib/release/ti_ipc_mm))
    $(shell $(MKDIR) package/lib/lib/release/ti_ipc_mm)
endif
ifeq (,$(wildcard package/lib/lib/release/ti_ipc_mm/package))
    $(shell $(MKDIR) package/lib/lib/release/ti_ipc_mm/package)
endif
endif
clean::
	-$(RMDIR) package


