/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-A71
 */

#ifndef ti_sysbios_family_arm_omap1030__
#define ti_sysbios_family_arm_omap1030__


/*
 * ======== module ti.sysbios.family.arm.omap1030.Hwi ========
 */

typedef struct ti_sysbios_family_arm_omap1030_Hwi_L1Intc ti_sysbios_family_arm_omap1030_Hwi_L1Intc;
typedef struct ti_sysbios_family_arm_omap1030_Hwi_L2Intc ti_sysbios_family_arm_omap1030_Hwi_L2Intc;
typedef struct ti_sysbios_family_arm_omap1030_Hwi_Module_State ti_sysbios_family_arm_omap1030_Hwi_Module_State;
typedef struct ti_sysbios_family_arm_omap1030_Hwi_Fxns__ ti_sysbios_family_arm_omap1030_Hwi_Fxns__;
typedef const ti_sysbios_family_arm_omap1030_Hwi_Fxns__* ti_sysbios_family_arm_omap1030_Hwi_Module;
typedef struct ti_sysbios_family_arm_omap1030_Hwi_Params ti_sysbios_family_arm_omap1030_Hwi_Params;
typedef struct ti_sysbios_family_arm_omap1030_Hwi_Object ti_sysbios_family_arm_omap1030_Hwi_Object;
typedef struct ti_sysbios_family_arm_omap1030_Hwi_Struct ti_sysbios_family_arm_omap1030_Hwi_Struct;
typedef ti_sysbios_family_arm_omap1030_Hwi_Object* ti_sysbios_family_arm_omap1030_Hwi_Handle;
typedef struct ti_sysbios_family_arm_omap1030_Hwi_Object__ ti_sysbios_family_arm_omap1030_Hwi_Instance_State;
typedef ti_sysbios_family_arm_omap1030_Hwi_Object* ti_sysbios_family_arm_omap1030_Hwi_Instance;

/*
 * ======== module ti.sysbios.family.arm.omap1030.Timer ========
 */

typedef struct ti_sysbios_family_arm_omap1030_Timer_Control ti_sysbios_family_arm_omap1030_Timer_Control;
typedef struct ti_sysbios_family_arm_omap1030_Timer_Module_State ti_sysbios_family_arm_omap1030_Timer_Module_State;
typedef struct ti_sysbios_family_arm_omap1030_Timer_Fxns__ ti_sysbios_family_arm_omap1030_Timer_Fxns__;
typedef const ti_sysbios_family_arm_omap1030_Timer_Fxns__* ti_sysbios_family_arm_omap1030_Timer_Module;
typedef struct ti_sysbios_family_arm_omap1030_Timer_Params ti_sysbios_family_arm_omap1030_Timer_Params;
typedef struct ti_sysbios_family_arm_omap1030_Timer_Object ti_sysbios_family_arm_omap1030_Timer_Object;
typedef struct ti_sysbios_family_arm_omap1030_Timer_Struct ti_sysbios_family_arm_omap1030_Timer_Struct;
typedef ti_sysbios_family_arm_omap1030_Timer_Object* ti_sysbios_family_arm_omap1030_Timer_Handle;
typedef struct ti_sysbios_family_arm_omap1030_Timer_Object__ ti_sysbios_family_arm_omap1030_Timer_Instance_State;
typedef ti_sysbios_family_arm_omap1030_Timer_Object* ti_sysbios_family_arm_omap1030_Timer_Instance;

/*
 * ======== module ti.sysbios.family.arm.omap1030.TimestampProvider ========
 */

typedef struct ti_sysbios_family_arm_omap1030_TimestampProvider_Module_State ti_sysbios_family_arm_omap1030_TimestampProvider_Module_State;
typedef struct ti_sysbios_family_arm_omap1030_TimestampProvider_Fxns__ ti_sysbios_family_arm_omap1030_TimestampProvider_Fxns__;
typedef const ti_sysbios_family_arm_omap1030_TimestampProvider_Fxns__* ti_sysbios_family_arm_omap1030_TimestampProvider_Module;


#endif /* ti_sysbios_family_arm_omap1030__ */ 
