/*
 *  Do not modify this file; it is automatically 
 *  generated and any modifications will be overwritten.
 *
 * @(#) xdc-A75
 */

#ifndef ti_sdo_ipc_family_f2837x__
#define ti_sdo_ipc_family_f2837x__


/*
 * ======== module ti.sdo.ipc.family.f2837x.IpcMgr ========
 */


/*
 * ======== module ti.sdo.ipc.family.f2837x.NameServerBlock ========
 */

typedef struct ti_sdo_ipc_family_f2837x_NameServerBlock_Message ti_sdo_ipc_family_f2837x_NameServerBlock_Message;
typedef struct ti_sdo_ipc_family_f2837x_NameServerBlock_Fxns__ ti_sdo_ipc_family_f2837x_NameServerBlock_Fxns__;
typedef const ti_sdo_ipc_family_f2837x_NameServerBlock_Fxns__* ti_sdo_ipc_family_f2837x_NameServerBlock_Module;
typedef struct ti_sdo_ipc_family_f2837x_NameServerBlock_Params ti_sdo_ipc_family_f2837x_NameServerBlock_Params;
typedef struct ti_sdo_ipc_family_f2837x_NameServerBlock_Object ti_sdo_ipc_family_f2837x_NameServerBlock_Object;
typedef struct ti_sdo_ipc_family_f2837x_NameServerBlock_Struct ti_sdo_ipc_family_f2837x_NameServerBlock_Struct;
typedef ti_sdo_ipc_family_f2837x_NameServerBlock_Object* ti_sdo_ipc_family_f2837x_NameServerBlock_Handle;
typedef struct ti_sdo_ipc_family_f2837x_NameServerBlock_Object__ ti_sdo_ipc_family_f2837x_NameServerBlock_Instance_State;
typedef ti_sdo_ipc_family_f2837x_NameServerBlock_Object* ti_sdo_ipc_family_f2837x_NameServerBlock_Instance;

/*
 * ======== module ti.sdo.ipc.family.f2837x.NotifyDriverCirc ========
 */

typedef struct ti_sdo_ipc_family_f2837x_NotifyDriverCirc_EventEntry ti_sdo_ipc_family_f2837x_NotifyDriverCirc_EventEntry;
typedef struct ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Fxns__ ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Fxns__;
typedef const ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Fxns__* ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Module;
typedef struct ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Params ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Params;
typedef struct ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Object ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Object;
typedef struct ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Struct ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Struct;
typedef ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Object* ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Handle;
typedef struct ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Object__ ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Instance_State;
typedef ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Object* ti_sdo_ipc_family_f2837x_NotifyDriverCirc_Instance;

/*
 * ======== module ti.sdo.ipc.family.f2837x.TransportCirc ========
 */

typedef struct ti_sdo_ipc_family_f2837x_TransportCirc_Module_State ti_sdo_ipc_family_f2837x_TransportCirc_Module_State;
typedef struct ti_sdo_ipc_family_f2837x_TransportCirc_Fxns__ ti_sdo_ipc_family_f2837x_TransportCirc_Fxns__;
typedef const ti_sdo_ipc_family_f2837x_TransportCirc_Fxns__* ti_sdo_ipc_family_f2837x_TransportCirc_Module;
typedef struct ti_sdo_ipc_family_f2837x_TransportCirc_Params ti_sdo_ipc_family_f2837x_TransportCirc_Params;
typedef struct ti_sdo_ipc_family_f2837x_TransportCirc_Object ti_sdo_ipc_family_f2837x_TransportCirc_Object;
typedef struct ti_sdo_ipc_family_f2837x_TransportCirc_Struct ti_sdo_ipc_family_f2837x_TransportCirc_Struct;
typedef ti_sdo_ipc_family_f2837x_TransportCirc_Object* ti_sdo_ipc_family_f2837x_TransportCirc_Handle;
typedef struct ti_sdo_ipc_family_f2837x_TransportCirc_Object__ ti_sdo_ipc_family_f2837x_TransportCirc_Instance_State;
typedef ti_sdo_ipc_family_f2837x_TransportCirc_Object* ti_sdo_ipc_family_f2837x_TransportCirc_Instance;


#endif /* ti_sdo_ipc_family_f2837x__ */ 
