/*==========================================================================*/
/*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
/*                      All Rights Reserved                                 */
/*==========================================================================*/

/**
 *  @file        iremap_merge_ti.h
 *
 *  @brief      This file defines the ivision interface for Remap Merge Applet
 *  @version 0.0 (January, 2014) : Base version.
 */

/** @ingroup    ti_ivision_REMAP_MERGE */
/*@{*/
#ifndef IREMAP_MERGE_TI_H
#define IREMAP_MERGE_TI_H

#include <ivision.h>
#include <ti/xdais/ires.h>

#include "remap_common.h"

#ifdef __cplusplus
    extern "C" {
#endif

/**
 * @brief The unique const funtion table for the REMAP_MERGE_TI.
 */
extern const IVISION_Fxns REMAP_MERGE_TI_VISION_FXNS;

/**
* @brief IRES interface of the REMAP_MERGE_TI_ algorithm
*/
extern const IRES_Fxns REMAP_MERGE_TI_IRES;


/**
  @brief User provides most of the infomration through buffer descriptor
         during process call. Below enums define the purpose of buffer
         There only 1 input buffers descriptor needed by this applet

  REMAP_MERGE_TI_BUFDESC_IN_IMAGEBUFFER: This buffer descriptor provides the
  actual image data required by applet.

  REMAP_MERGE_TI_BUFDESC_IN_LUTBUFFER: This buffer descriptor provides the
  Look up Table required by applet.

  REMAP_MERGE_TI_BUFDESC_IN_MERGEBUFFER: This buffer descriptor provides the
  merge frame required by applet.

  REMAP_MERGE_TI_BUFDESC_IN_ALPHABUFFER: This buffer descriptor provides the
  alpha frame required by applet.

  REMAP_MERGE_TI_BUFDESC_IN_REMAP_TOTAL: Total number of Remap buffer descriptors
  when Merge is not enabled.

  REMAP_MERGE_TI_BUFDESC_IN_REMAP_MERGE_TOTAL: Total number of Remap buffer descriptors
  when Merge is enabled.

*/
typedef enum
{
  REMAP_MERGE_TI_BUFDESC_IN_IMAGEBUFFER = 0,
  REMAP_MERGE_TI_BUFDESC_IN_LUTBUFFER   = 1,
  REMAP_MERGE_TI_BUFDESC_IN_MERGEBUFFER = 2,
  REMAP_MERGE_TI_BUFDESC_IN_ALPHABUFFER = 3,
  REMAP_MERGE_TI_BUFDESC_IN_REMAP_TOTAL = REMAP_MERGE_TI_BUFDESC_IN_LUTBUFFER + 1U,
  REMAP_MERGE_TI_BUFDESC_IN_REMAP_MERGE_TOTAL = REMAP_MERGE_TI_BUFDESC_IN_ALPHABUFFER + 1U
} IREMAP_MERGE_InBufOrder ;

/**
  @brief User provides most of the information through buffer descriptor
         during process call. Below enums define the purpose of out buffer

  REMAP_MERGE_TI_BUFDESC_OUT_REMAPBUFFER: This buffer descriptor provides the
  image output generated by applet.

*/

typedef enum
{
  REMAP_MERGE_TI_BUFDESC_OUT_REMAPBUFFER = 0,
  REMAP_MERGE_TI_BUFDESC_OUT_TOTAL
} IREMAP_MERGE_OutBufOrder ;


/**

  @struct REMAP_MERGE_TI_CreateParams
  @brief  This structure contains all the parameters which controls
          Remap and Merge applet at create time

  @param  visionParams
          Common parmeters for all ivison based modules

  @param  remapParams
          param structure to configure Remap

  @param  enableMerge
          Boolean to enable and disable Alpha Blend

  @param  dstFormat
          Format of output.
*/
typedef struct
{
  IVISION_Params visionParams;
  RemapParms     remapParams;
  uint8_t        enableMerge;
  Format         dstFormat;

} REMAP_MERGE_TI_CreateParams;


#ifdef __cplusplus
 }
#endif

/*@}*/
/* ti_ivision_REMAP_MERGE */

#endif /*IREMAP_MERGE_TI_H */
/*==========================================================================*/
/*     END of the FILE                                                      */
/*==========================================================================*/


