/*------------------------------------------------------------------------*/
/* NAME: merge_sort_kernel_hard.c                                         */
/*                                                                        */
/* AUTHOR: J.Sankaran                                                     */
/*                                                                        */
/* REVISON HISTORY:                                                       */
/* 04/16/13.........Wrote initial version of code.............J.Sankaran  */
/*                                                                        */
/* DESCRIPTION:                                                           */
/*                                                                        */
/* The default compiler generated performs a buffer switch, init.         */
/* with known static arrays, buffer switch again followed by execution.   */
/* We want to initialize various functions and seek deferred execution    */
/* so that we can better pipeline the execution of several back to        */
/* back functions. We therefore pick up the basic file generated by       */
/* the compiler and modify it to do only initialization, using the        */
/* parameter array passed.                                                */
/*                                                                        */
/* The function has the following prototype:                              */
/*                                                                        */
/* 1. void my_vcop_sort8_simd8_64_custom                                  */
/*    (                                                                   */
/*       int             niter,                                           */
/*       int             out_tr,                                          */
/*       __vptr_uint32    in,                                              */
/*       __vptr_uint32    out,                                             */
/*       unsigned short  *pblock                                          */
/*    )                                                                   */
/*                                                                        */
/*    This function does custom initialization for one 8x8 block sort     */
/*    of 64 elements, while doing a transpose.                            */
/*                                                                        */
/*    2. void my_vcop_sort8_simd8_XX_custom                               */
/*       (                                                                */
/*          int              niter,                                       */
/*          int              out_tr,                                      */
/*          __vptr_uint32     in,                                          */
/*          __vptr_uint32     out,                                         */
/*          unsigned short   *pblock                                      */
/*       )                                                                */
/*                                                                        */
/*    This function performs the custom initialization for N 8x8 blocks   */
/*    doing a block sort, without transposing the output.                 */
/*                                                                        */
/*    3. void my_vcop_psort2_1step_reverse_kernel_custom                  */
/*       (                                                                */
/*          int              niter1,                                      */
/*          int              niter2,                                      */
/*          int              niter3,                                      */
/*          int              ibase_0,                                     */
/*          int              ibase_1,                                     */
/*          int              in1ptr_w1,                                   */
/*          int              in1ptr_w2,                                   */
/*          int              in1ptr_w3,                                   */
/*          int              in2ptr_w1,                                   */
/*          int              in2ptr_w2,                                   */
/*          int              in2ptr_w3,                                   */
/*          int              obase_0,                                     */
/*          int              obase_1,                                     */
/*          int              outptr_w1,                                   */
/*          int              outptr_w2,                                   */
/*          int              outptr_w3,                                   */
/*           __vptr_uint32     input,                                      */
/*           __vptr_uint32     output,                                     */
/*           __vptr_int32     out_ofst,                                   */
/*           unsigned short   *pblock                                     */
/*         )                                                              */
/*                                                                        */
/*    This function is the custom initialization function for 1step       */
/*    input data for 2nd leg being read in a reversed fashion.            */
/*                                                                        */
/*    In a similar manner, we have functions for initializing 1step,      */
/*    2step reverse, 2step, 3stepreverse, 3step, remove_ex_col.           */
/*                                                                        */
/* ASSUMPTIONS:                                                           */
/*                                                                        */
/* User manages parameter memory allocation and passes a pointer, to      */
/* the area, where values are to be allocated.                            */
/*                                                                        */
/*------------------------------------------------------------------------*/
/* Texas Instruments Incorporated 2010-2012.                              */
/*========================================================================*/

#if VCOP_HOST_EMULATION
#include <vcop_host.h>
#endif

#include <vcop.h>


#include "merge_sort_kernel.h"

#if !(VCOP_HOST_EMULATION)

void my_vcop_sort8_simd8_64_custom
(
   int             niter,
   int             out_tr,
   __vptr_uint32    in,
   __vptr_uint32    out,
   unsigned short  *pblock
)
{
   vcop_sort8_simd8_64_init(niter, out_tr, in, out, pblock);
}

void my_vcop_sort8_simd8_XX_custom
(
   int              niter,
   int              out_tr,
   __vptr_uint32     in,
   __vptr_uint32     out,
   unsigned short   *pblock
)
{
   vcop_sort8_simd8_XX_init(niter, out_tr, in, out, pblock);
}

void my_vcop_psort2_1step_reverse_kernel_custom
(
   int              niter1,
   int              niter2,
   int              niter3,
   int              ibase_0,
   int              ibase_1,
   int              in1ptr_w1,
   int              in1ptr_w2,
   int              in1ptr_w3,
   int              in2ptr_w1,
   int              in2ptr_w2,
   int              in2ptr_w3,
   int              obase_0,
   int              obase_1,
   int              outptr_w1,
   int              outptr_w2,
   int              outptr_w3,
   __vptr_uint32     input,
   __vptr_uint32     output,
   __vptr_int32     out_ofst,
   unsigned short   *pblock
)
{
   vcop_psort2_1step_reverse_kernel_init(niter1, niter2, niter3, ibase_0, ibase_1, in1ptr_w1, in1ptr_w2, in1ptr_w3, in2ptr_w1, in2ptr_w2, in2ptr_w3, obase_0, obase_1, outptr_w1, outptr_w2, outptr_w3, input, output, out_ofst, pblock);
}


void my_vcop_psort2_1step_kernel_custom
(
   int               niter1,
   int               niter2,
   int               niter3,
   int               ibase_0,
   int               ibase_1,
   int               in1ptr_w1,
   int               in1ptr_w2,
   int               in1ptr_w3,
   int               in2ptr_w1,
   int               in2ptr_w2,
   int               in2ptr_w3,
   int               obase_0,
   int               obase_1,
   int               outptr_w1,
   int               outptr_w2,
   int               outptr_w3,
   __vptr_uint32      input,
   __vptr_uint32      output,
   __vptr_int32      out_ofst,
   unsigned short    *pblock)
{
   VCOP_BUF_SWITCH_SET(WBUF_SYST, IBUFHB_SYST, IBUFLB_SYST, IBUFHA_SYST, IBUFLA_SYST);

   vcop_psort2_1step_kernel_init(niter1, niter2, niter3, ibase_0, ibase_1, in1ptr_w1, in1ptr_w2, in1ptr_w3, in2ptr_w1, in2ptr_w2, in2ptr_w3, obase_0, obase_1, outptr_w1, outptr_w2, outptr_w3, input, output, out_ofst, pblock);
}


void my_vcop_psort2_2steps_reverse_kernel_custom
(
   int               niter1,
   int               niter2,
   int               niter3,
   int               ibase_0,
   int               ibase_1,
   int               ibase_2,
   int               ibase_3,
   int               in1ptr_w1,
   int               in1ptr_w2,
   int               in1ptr_w3,
   int               in2ptr_w1,
   int               in2ptr_w2,
   int               in2ptr_w3,
   int               obase_0,
   int               obase_1,
   int               obase_2,
   int               obase_3,
   int               outptr_w1,
   int               outptr_w2,
   int               outptr_w3,
   __vptr_uint32      input,
   __vptr_uint32      output,
   __vptr_int32      out_ofst,
   unsigned short    *pblock
)
{
   vcop_psort2_2steps_reverse_kernel_init(niter1, niter2, niter3, ibase_0, ibase_1, ibase_2, ibase_3, in1ptr_w1, in1ptr_w2, in1ptr_w3, in2ptr_w1, in2ptr_w2, in2ptr_w3, obase_0, obase_1, obase_2, obase_3, outptr_w1, outptr_w2, outptr_w3, input, output, out_ofst, pblock);
}

void my_vcop_psort2_2steps_kernel_custom
(
   int               niter1,
   int               niter2,
   int               niter3,
   int               ibase_0,
   int               ibase_1,
   int               ibase_2,
   int               ibase_3,
   int               in1ptr_w1,
   int               in1ptr_w2,
   int               in1ptr_w3,
   int               in2ptr_w1,
   int               in2ptr_w2,
   int               in2ptr_w3,
   int               obase_0,
   int               obase_1,
   int               obase_2,
   int               obase_3,
   int               outptr_w1,
   int               outptr_w2,
   int               outptr_w3,
   __vptr_uint32      input,
   __vptr_uint32      output,
   __vptr_int32      out_ofst,
   unsigned short    *pblock
)
{
   vcop_psort2_2steps_kernel_init(niter1, niter2, niter3, ibase_0, ibase_1, ibase_2, ibase_3, in1ptr_w1, in1ptr_w2, in1ptr_w3, in2ptr_w1, in2ptr_w2, in2ptr_w3, obase_0, obase_1, obase_2, obase_3, outptr_w1, outptr_w2, outptr_w3, input, output, out_ofst, pblock);
}

void my_vcop_psort2_3steps_reverse_kernel_custom
(
   int               niter1,
   int               niter2,
   int               niter3,
   int               ibase_0,
   int               ibase_1,
   int               ibase_2,
   int               ibase_3,
   int               ibase_4,
   int               ibase_5,
   int               ibase_6,
   int               ibase_7,
   int               in1ptr_w1,
   int               in1ptr_w2,
   int               in1ptr_w3,
   int               in2ptr_w1,
   int               in2ptr_w2,
   int               in2ptr_w3,
   int               obase_0,
   int               obase_1,
   int               obase_2,
   int               obase_3,
   int               obase_4,
   int               obase_5,
   int               obase_6,
   int               obase_7,
   int               outptr_w1,
   int               outptr_w2,
   int               outptr_w3,
   __vptr_uint32      input,
   __vptr_uint32      output,
   __vptr_int32      out_ofst,
   unsigned short    *pblock
)
{
   vcop_psort2_3steps_reverse_kernel_init(niter1, niter2, niter3, ibase_0, ibase_1, ibase_2, ibase_3, ibase_4, ibase_5, ibase_6, ibase_7, in1ptr_w1, in1ptr_w2, in1ptr_w3, in2ptr_w1, in2ptr_w2, in2ptr_w3, obase_0, obase_1, obase_2, obase_3, obase_4, obase_5, obase_6, obase_7, outptr_w1, outptr_w2, outptr_w3, input, output, out_ofst, pblock);
}


void my_vcop_psort2_3steps_kernel_custom
(
   int                niter1,
   int                niter2,
   int                niter3,
   int                ibase_0,
   int                ibase_1,
   int                ibase_2,
   int                ibase_3,
   int                ibase_4,
   int                ibase_5,
   int                ibase_6,
   int                ibase_7,
   int                in1ptr_w1,
   int                in1ptr_w2,
   int                in1ptr_w3,
   int                in2ptr_w1,
   int                in2ptr_w2,
   int                in2ptr_w3,
   int                obase_0,
   int                obase_1,
   int                obase_2,
   int                obase_3,
   int                obase_4,
   int                obase_5,
   int                obase_6,
   int                obase_7,
   int                outptr_w1,
   int                outptr_w2,
   int                outptr_w3,
   __vptr_uint32       input,
   __vptr_uint32       output,
   __vptr_int32       out_ofst,
   unsigned short     *pblock
)
{
   vcop_psort2_3steps_kernel_init(niter1, niter2, niter3, ibase_0, ibase_1, ibase_2, ibase_3, ibase_4, ibase_5, ibase_6, ibase_7, in1ptr_w1, in1ptr_w2, in1ptr_w3, in2ptr_w1, in2ptr_w2, in2ptr_w3, obase_0, obase_1, obase_2, obase_3, obase_4, obase_5, obase_6, obase_7, outptr_w1, outptr_w2, outptr_w3, input, output, out_ofst, pblock);
}

void my_vcop_remove_ex_col_custom
(
   __vptr_uint32       input,
   __vptr_uint32       output,
   int                nitems,
   unsigned short     *pblock
)
{
   vcop_remove_ex_col_init(input, output, nitems, pblock);
}

#endif
/*------------------------------------------------------------------------*/
/* End of file:  merge_sort_kernel_hard.c                                 */
/*------------------------------------------------------------------------*/
/* Texas Instruments Incorporated 2010-2012.                              */
/*========================================================================*/

