/*
*******************************************************************************
*
* Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
* ALL RIGHTS RESERVED
*
*******************************************************************************
*/

/*
*******************************************************************************
*
* IMPORTANT NOTE:
*  This file is AUTO-GENERATED by Vision SDK use case generation tool
*
*******************************************************************************
*/
#include "chains_lvdsVipMultiCam_Display_tda2xx_mc_priv.h"
Void chains_lvdsVipMultiCam_Display_tda2xx_mc_SetLinkId(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj){
       pObj->CaptureLinkID                  = SYSTEM_LINK_ID_CAPTURE_0;
       pObj->VPELinkID                      = SYSTEM_LINK_ID_VPE_0;
       pObj->SyncLinkID                     = IPU1_0_LINK (SYSTEM_LINK_ID_SYNC_0);
       pObj->Alg_DmaSwMsLinkID              = IPU1_0_LINK (SYSTEM_LINK_ID_ALG_0);
       pObj->Display_videoLinkID            = SYSTEM_LINK_ID_DISPLAY_0;
}

Void chains_lvdsVipMultiCam_Display_tda2xx_mc_ResetLinkPrms(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj){
       CaptureLink_CreateParams_Init(&pObj->CapturePrm);
       VpeLink_CreateParams_Init(&pObj->VPEPrm);
       SyncLink_CreateParams_Init(&pObj->SyncPrm);
       AlgorithmLink_DmaSwMsCreateParams_Init(&pObj->Alg_DmaSwMsPrm);
       DisplayLink_CreateParams_Init(&pObj->Display_videoPrm);
}

Void chains_lvdsVipMultiCam_Display_tda2xx_mc_SetPrms(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj){
       (pObj->Alg_DmaSwMsPrm).baseClassCreate.size  = sizeof(AlgorithmLink_DmaSwMsCreateParams);
       (pObj->Alg_DmaSwMsPrm).baseClassCreate.algId  = ALGORITHM_LINK_IPU_ALG_DMA_SWMS;
}

Void chains_lvdsVipMultiCam_Display_tda2xx_mc_ConnectLinks(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj){

       //Capture -> VPE
       pObj->CapturePrm.outQueParams.nextLink = pObj->VPELinkID;
       pObj->VPEPrm.inQueParams.prevLinkId = pObj->CaptureLinkID;
       pObj->VPEPrm.inQueParams.prevLinkQueId = 0;

       //VPE -> Sync
       pObj->VPEPrm.outQueParams[0].nextLink = pObj->SyncLinkID;
       pObj->SyncPrm.inQueParams.prevLinkId = pObj->VPELinkID;
       pObj->SyncPrm.inQueParams.prevLinkQueId = 0;

       //Sync -> Alg_DmaSwMs
       pObj->SyncPrm.outQueParams.nextLink = pObj->Alg_DmaSwMsLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkId = pObj->SyncLinkID;
       pObj->Alg_DmaSwMsPrm.inQueParams.prevLinkQueId = 0;

       //Alg_DmaSwMs -> Display_video
       pObj->Alg_DmaSwMsPrm.outQueParams.nextLink = pObj->Display_videoLinkID;
       pObj->Display_videoPrm.inQueParams.prevLinkId = pObj->Alg_DmaSwMsLinkID;
       pObj->Display_videoPrm.inQueParams.prevLinkQueId = 0;

}

Int32 chains_lvdsVipMultiCam_Display_tda2xx_mc_Create(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj, Void *appObj){

       Int32 status;

       chains_lvdsVipMultiCam_Display_tda2xx_mc_SetLinkId(pObj);
       chains_lvdsVipMultiCam_Display_tda2xx_mc_ResetLinkPrms(pObj);

       chains_lvdsVipMultiCam_Display_tda2xx_mc_SetPrms(pObj);
       chains_lvdsVipMultiCam_Display_tda2xx_mc_SetAppPrms(pObj, appObj);

       chains_lvdsVipMultiCam_Display_tda2xx_mc_ConnectLinks(pObj);
       status = System_linkCreate(pObj->CaptureLinkID, &pObj->CapturePrm, sizeof(pObj->CapturePrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->VPELinkID, &pObj->VPEPrm, sizeof(pObj->VPEPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->SyncLinkID, &pObj->SyncPrm, sizeof(pObj->SyncPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Alg_DmaSwMsLinkID, &pObj->Alg_DmaSwMsPrm, sizeof(pObj->Alg_DmaSwMsPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkCreate(pObj->Display_videoLinkID, &pObj->Display_videoPrm, sizeof(pObj->Display_videoPrm));
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Display_tda2xx_mc_Start(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj){

       Int32 status;

       status = System_linkStart(pObj->Display_videoLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStart(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Display_tda2xx_mc_Stop(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj){

       Int32 status;

       status = System_linkStop(pObj->Display_videoLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkStop(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Int32 chains_lvdsVipMultiCam_Display_tda2xx_mc_Delete(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj){

       Int32 status;

       status = System_linkDelete(pObj->Display_videoLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->Alg_DmaSwMsLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->SyncLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->VPELinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       status = System_linkDelete(pObj->CaptureLinkID);
       UTILS_assert(status == SYSTEM_LINK_STATUS_SOK);

       return status;
}

Void chains_lvdsVipMultiCam_Display_tda2xx_mc_printBufferStatistics(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj){
       System_linkPrintBufferStatistics(pObj->CaptureLinkID);
       System_linkPrintBufferStatistics(pObj->VPELinkID);
       System_linkPrintBufferStatistics(pObj->SyncLinkID);
       System_linkPrintBufferStatistics(pObj->Alg_DmaSwMsLinkID);
       System_linkPrintBufferStatistics(pObj->Display_videoLinkID);
       Task_sleep(500);
}

Void chains_lvdsVipMultiCam_Display_tda2xx_mc_printStatistics(chains_lvdsVipMultiCam_Display_tda2xx_mcObj *pObj){
       System_linkPrintStatistics(pObj->CaptureLinkID);
       System_linkPrintStatistics(pObj->VPELinkID);
       System_linkPrintStatistics(pObj->SyncLinkID);
       System_linkPrintStatistics(pObj->Alg_DmaSwMsLinkID);
       System_linkPrintStatistics(pObj->Display_videoLinkID);
       Task_sleep(500);
}

