/* ======================================================================
 *   Copyright (C) 2014 Texas Instruments Incorporated
 *
 *   All rights reserved. Property of Texas Instruments Incorporated.
 *   Restricted rights to use, duplicate or disclose this code are
 *   granted through contract.
 *
 *   The program may not be used without the written permission
 *   of Texas Instruments Incorporated or against the terms and conditions
 *   stipulated in the agreement under which this program has been
 *   supplied.
 * ==================================================================== */
/**
 * \file        stw_boardTda2xxPinmuxData.c
 *
 * \brief       This file contains the pin mux configurations for the TDA2XX
 *              EVM. These are prepared based on how the peripherals are
 *              extended on the boards.
 *
 */

/* ========================================================================== */
/*                             Include Files                                  */
/* ========================================================================== */
#include "stdint.h"
#include <common/stw_dataTypes.h>
#include <common/stw_types.h>
#include <common/stw_config.h>
#include <common/trace.h>
#include "i2clib/lld_hsi2c.h"
#include <boards/stw_board.h>
#include "devices/stw_device.h"
#include "hw_ctrl_core_pad_io.h"
#include "stw_boardPriv.h"

/* ========================================================================== */
/*                         Structures and Enums                               */
/* ========================================================================== */

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/* Peripheral Pin Configurations */

boardPinmuxBoardCfg_t gBoardTda2xxPinMuxData[] =
{
    /* pin mux for UART1 RXD pin */
    {DEVICE_ID_UART,         DEVICE_UART_INST_ID_1,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_UART1_RXD, 0x40000},
    /* pin mux for UART1 TXD pin */
    {DEVICE_ID_UART,         DEVICE_UART_INST_ID_1,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_UART1_TXD, 0x0},
    /* pin mux for UART2 RXD pin */
    {DEVICE_ID_UART,         DEVICE_UART_INST_ID_2,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_UART2_RXD, 0x40000},
    /* pin mux for UART2 TXD pin */
    {DEVICE_ID_UART,         DEVICE_UART_INST_ID_2,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_UART2_TXD, 0x0},
    /* pin mux for UART3 RXD pin */
    {DEVICE_ID_UART,         DEVICE_UART_INST_ID_3,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_SPI2_SCLK, 0x40001},
    /* pin mux for UART3 TXD pin */
    {DEVICE_ID_UART,         DEVICE_UART_INST_ID_3,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_SPI2_D1, 0x1},
    /* pin mux for I2C1 mux */
    {DEVICE_ID_I2C,          DEVICE_I2C_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_I2C1_SDA, 0x60000},
    {DEVICE_ID_I2C,          DEVICE_I2C_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_I2C1_SCL, 0x60000},
    /* pin mux for I2C2 mux */
    {DEVICE_ID_I2C,          DEVICE_I2C_INST_ID_1,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_I2C2_SDA, 0x60000},
    {DEVICE_ID_I2C,          DEVICE_I2C_INST_ID_1,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_I2C2_SCL, 0x60000},
    /* pin mux for VOUT1 mux  */
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_CLK, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_DE, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_FLD, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_HSYNC, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_VSYNC, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D0, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D1, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D2, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D3, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D4, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D5, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D6, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D7, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D8, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D9, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D10, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D11, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D12, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D13, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D14, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D15, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D16, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D17, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D18, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D19, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D20, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D21, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D22, 0x40000},
    {DEVICE_MODULE_ID_DCTRL, DEVICE_MODULE_DSS_DISPC_OVLY_DPI1_INST_ID_0,
     BOARD_MODE_DEFAULT, CTRL_CORE_PAD_VOUT1_D23, 0x40000},
    /* pin mux for VIN1A mux  */
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_8BIT | BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT | BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_CLK0, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_8BIT | BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT | BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_DE0, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_8BIT | BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT | BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_FLD0, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_8BIT | BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT | BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_HSYNC0, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_8BIT | BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT | BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_VSYNC0, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_BT656 |
      BOARD_MODE_VIDEO_8BIT |
      BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D0, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_BT656 |
      BOARD_MODE_VIDEO_8BIT |
      BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D1, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_BT656 |
      BOARD_MODE_VIDEO_8BIT |
      BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D2, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_BT656 |
      BOARD_MODE_VIDEO_8BIT |
      BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D3, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_BT656 |
      BOARD_MODE_VIDEO_8BIT |
      BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D4, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_BT656 |
      BOARD_MODE_VIDEO_8BIT |
      BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D5, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_BT656 |
      BOARD_MODE_VIDEO_8BIT |
      BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D6, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_BT656 |
      BOARD_MODE_VIDEO_8BIT |
      BOARD_MODE_VIDEO_10BIT | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D7, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_10BIT |
      BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT | BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D8, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_10BIT |
      BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT | BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D9, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D10, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_12BIT |
      BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D11, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT |
      BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D12, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_14BIT |
      BOARD_MODE_VIDEO_16BIT |
      BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D13, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D14, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_BT1120 | BOARD_MODE_VIDEO_16BIT | BOARD_MODE_VIDEO_24BIT),
     CTRL_CORE_PAD_VIN1A_D15, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D16, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D17, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D18, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D19, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D20, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D21, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D22, 0x40000},
    {DEVICE_MODULE_ID_VIP,   DEVICE_MODULE_VIP1_S0_PORTA_INST_ID_0,
     (BOARD_MODE_VIDEO_24BIT), CTRL_CORE_PAD_VIN1A_D23, 0x40000},
    {DEVICE_ID_INVALID,      0,                                          0,0, 0},
};
