/*
 *  Copyright 2015 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) ti.targets.arm.elf; 1, 0, 0,0; 7-10-2015 12:06:13; /db/ztree/library/trees/xdctargets/xdctargets-j04/src/ xlibrary

 */

