# /*==========================================================================*/
# /*      Copyright (C) 2009-2013 Texas Instruments Incorporated.             */
# /*                      All Rights Reserved                                 */
# /*==========================================================================*/
FILE = vcop_canny_applet
TEST_BENCH = vcop_canny_tb
CFILES = 
include ../../../common/Makefile.wincommon
