	cd /boot
	for DTB_FILE in dra72-evm.dtb dra72-evm-lcd10.dtb dra72-evm-lcd7.dtb dra7-evm.dtb dra7-evm-lcd10.dtb dra7-evm-lcd7.dtb
	do
		DTB_BASE_NAME=`basename ${DTB_FILE} | awk -F "." '{print $1}'`
		DTB_SYMLINK_NAME=`echo zImage-dra7xx-evm | sed "s/dra7xx-evm/${DTB_BASE_NAME}/g"`
		update-alternatives --install /boot/${DTB_BASE_NAME}.dtb ${DTB_BASE_NAME}.dtb devicetree-${DTB_SYMLINK_NAME}.dtb 31449 || true
	done
