/* ------------------------------------------------------------------------ */
/*          Copyright (C) 2013 Texas Instruments, Incorporated.             */
/*                          All Rights Reserved.                            */
/* ======================================================================== */
#pragma CHECK_MISRA ("none")
#include <stdio.h>
#include "configparser.h"
#include "disparity_config.h"
#pragma RESET_MISRA ("required")

uint32_t disparity_numTestCases;
int8_t disparity_skipValidation;

sdisparity_Config gConfig_disparity[EVELIB_DISPARITY_NUM_TESTCASES];

sTokenMapping gsTokenMap_disparity[] =
{
        {(char* )"numTestCases",           &disparity_numTestCases         , INT_32, SINGLE},
        {(char* )"skipValidation",         &disparity_skipValidation       , INT_8, SINGLE},

        {(char* )"inImageLeft",           &gConfig_disparity[0].inImageLeft         , STRING, SINGLE},
        {(char* )"inImageRight",          &gConfig_disparity[0].inImageRight        , STRING, SINGLE},
        {(char* )"srcImageWidth",         &gConfig_disparity[0].srcImageWidth       , INT_32, SINGLE},
        {(char* )"srcImageHeight",        &gConfig_disparity[0].srcImageHeight      , INT_32, SINGLE},
        {(char* )"srcImagePitchL",        &gConfig_disparity[0].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"srcImagePitchR",        &gConfig_disparity[0].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"outImage",              &gConfig_disparity[0].outImage             , STRING, SINGLE},
        {(char* )"dstImagePitch",         &gConfig_disparity[0].dstImagePitch       , INT_32, SINGLE},
        {(char* )"pattern",               &gConfig_disparity[0].pattern             , INT_8 , SINGLE},
        {(char* )"inputBitDepth",         &gConfig_disparity[0].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"winWidth",              &gConfig_disparity[0].winWidth            , INT_8 , SINGLE},
        {(char* )"winHeight",             &gConfig_disparity[0].winHeight           , INT_8 , SINGLE},
        {(char* )"numDisparities",        &gConfig_disparity[0].numDisparities      , INT_16 , SINGLE},
        {(char* )"disparityStep",         &gConfig_disparity[0].disparityStep       , INT_8 , SINGLE},
        {(char* )"searchDir",             &gConfig_disparity[0].searchDir           , INT_8 , SINGLE},
        {(char* )"outputCostType",        &gConfig_disparity[0].outputCostType      , INT_8 , SINGLE},
        
        {(char* )"0inImageLeft",           &gConfig_disparity[0].inImageLeft         , STRING, SINGLE},
        {(char* )"0inImageRight",          &gConfig_disparity[0].inImageRight        , STRING, SINGLE},
        {(char* )"0srcImageWidth",         &gConfig_disparity[0].srcImageWidth       , INT_32, SINGLE},
        {(char* )"0srcImageHeight",        &gConfig_disparity[0].srcImageHeight      , INT_32, SINGLE},
        {(char* )"0srcImagePitchL",        &gConfig_disparity[0].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"0srcImagePitchR",        &gConfig_disparity[0].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"0outImage",              &gConfig_disparity[0].outImage         	  , STRING, SINGLE},
        {(char* )"0dstImagePitch",         &gConfig_disparity[0].dstImagePitch       , INT_32, SINGLE},
        {(char* )"0pattern",               &gConfig_disparity[0].pattern             , INT_8 , SINGLE},
        {(char* )"0inputBitDepth",       &gConfig_disparity[0].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"0winWidth",              &gConfig_disparity[0].winWidth            , INT_8 , SINGLE},
        {(char* )"0winHeight",             &gConfig_disparity[0].winHeight           , INT_8 , SINGLE},
        {(char* )"0numDisparities",        &gConfig_disparity[0].numDisparities      , INT_16 , SINGLE},
        {(char* )"0disparityStep",         &gConfig_disparity[0].disparityStep       , INT_8 , SINGLE},
        {(char* )"0searchDir",             &gConfig_disparity[0].searchDir           , INT_8 , SINGLE},
        {(char* )"0outputCostType",        &gConfig_disparity[0].outputCostType      , INT_8 , SINGLE},
        
        {(char* )"1inImageLeft",           &gConfig_disparity[1].inImageLeft         , STRING, SINGLE},
        {(char* )"1inImageRight",          &gConfig_disparity[1].inImageRight        , STRING, SINGLE},
        {(char* )"1srcImageWidth",         &gConfig_disparity[1].srcImageWidth       , INT_32, SINGLE},
        {(char* )"1srcImageHeight",        &gConfig_disparity[1].srcImageHeight      , INT_32, SINGLE},
        {(char* )"1srcImagePitchL",        &gConfig_disparity[1].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"1srcImagePitchR",        &gConfig_disparity[1].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"1outImage",              &gConfig_disparity[1].outImage            , STRING, SINGLE},
        {(char* )"1dstImagePitch",         &gConfig_disparity[1].dstImagePitch       , INT_32, SINGLE},
        {(char* )"1pattern",               &gConfig_disparity[1].pattern             , INT_8 , SINGLE},
        {(char* )"1inputBitDepth",       &gConfig_disparity[1].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"1winWidth",              &gConfig_disparity[1].winWidth            , INT_8 , SINGLE},
        {(char* )"1winHeight",             &gConfig_disparity[1].winHeight           , INT_8 , SINGLE},
        {(char* )"1numDisparities",        &gConfig_disparity[1].numDisparities      , INT_16 , SINGLE},
        {(char* )"1disparityStep",         &gConfig_disparity[1].disparityStep       , INT_8 , SINGLE},
        {(char* )"1searchDir",             &gConfig_disparity[1].searchDir           , INT_8 , SINGLE},
        {(char* )"1outputCostType",        &gConfig_disparity[1].outputCostType      , INT_8 , SINGLE},

        {(char* )"2inImageLeft",           &gConfig_disparity[2].inImageLeft         , STRING, SINGLE},
        {(char* )"2inImageRight",          &gConfig_disparity[2].inImageRight        , STRING, SINGLE},
        {(char* )"2srcImageWidth",         &gConfig_disparity[2].srcImageWidth       , INT_32, SINGLE},
        {(char* )"2srcImageHeight",        &gConfig_disparity[2].srcImageHeight      , INT_32, SINGLE},
        {(char* )"2srcImagePitchL",        &gConfig_disparity[2].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"2srcImagePitchR",        &gConfig_disparity[2].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"2outImage",              &gConfig_disparity[2].outImage            , STRING, SINGLE},
        {(char* )"2dstImagePitch",         &gConfig_disparity[2].dstImagePitch       , INT_32, SINGLE},
        {(char* )"2pattern",               &gConfig_disparity[2].pattern             , INT_8 , SINGLE},
        {(char* )"2inputBitDepth",       &gConfig_disparity[2].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"2winWidth",              &gConfig_disparity[2].winWidth            , INT_8 , SINGLE},
        {(char* )"2winHeight",             &gConfig_disparity[2].winHeight           , INT_8 , SINGLE},
        {(char* )"2numDisparities",        &gConfig_disparity[2].numDisparities      , INT_16 , SINGLE},
        {(char* )"2disparityStep",         &gConfig_disparity[2].disparityStep       , INT_8 , SINGLE},
        {(char* )"2searchDir",             &gConfig_disparity[2].searchDir           , INT_8 , SINGLE},
        {(char* )"2outputCostType",        &gConfig_disparity[2].outputCostType      , INT_8 , SINGLE},

        {(char* )"3inImageLeft",           &gConfig_disparity[3].inImageLeft         , STRING, SINGLE},
        {(char* )"3inImageRight",          &gConfig_disparity[3].inImageRight        , STRING, SINGLE},
        {(char* )"3srcImageWidth",         &gConfig_disparity[3].srcImageWidth       , INT_32, SINGLE},
        {(char* )"3srcImageHeight",        &gConfig_disparity[3].srcImageHeight      , INT_32, SINGLE},
        {(char* )"3srcImagePitchL",        &gConfig_disparity[3].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"3srcImagePitchR",        &gConfig_disparity[3].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"3outImage",              &gConfig_disparity[3].outImage            , STRING, SINGLE},
        {(char* )"3dstImagePitch",         &gConfig_disparity[3].dstImagePitch       , INT_32, SINGLE},
        {(char* )"3pattern",               &gConfig_disparity[3].pattern             , INT_8 , SINGLE},
        {(char* )"3inputBitDepth",       &gConfig_disparity[3].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"3winWidth",              &gConfig_disparity[3].winWidth            , INT_8 , SINGLE},
        {(char* )"3winHeight",             &gConfig_disparity[3].winHeight           , INT_8 , SINGLE},
        {(char* )"3numDisparities",        &gConfig_disparity[3].numDisparities      , INT_16 , SINGLE},
        {(char* )"3disparityStep",         &gConfig_disparity[3].disparityStep       , INT_8 , SINGLE},
        {(char* )"3searchDir",             &gConfig_disparity[3].searchDir           , INT_8 , SINGLE},
        {(char* )"3outputCostType",        &gConfig_disparity[3].outputCostType      , INT_8 , SINGLE},
        
        {(char* )"4inImageLeft",           &gConfig_disparity[4].inImageLeft         , STRING, SINGLE},
        {(char* )"4inImageRight",          &gConfig_disparity[4].inImageRight        , STRING, SINGLE},
        {(char* )"4srcImageWidth",         &gConfig_disparity[4].srcImageWidth       , INT_32, SINGLE},
        {(char* )"4srcImageHeight",        &gConfig_disparity[4].srcImageHeight      , INT_32, SINGLE},
        {(char* )"4srcImagePitchL",        &gConfig_disparity[4].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"4srcImagePitchR",        &gConfig_disparity[4].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"4outImage",              &gConfig_disparity[4].outImage            , STRING, SINGLE},
        {(char* )"4dstImagePitch",         &gConfig_disparity[4].dstImagePitch       , INT_32, SINGLE},
        {(char* )"4pattern",               &gConfig_disparity[4].pattern             , INT_8 , SINGLE},
        {(char* )"4inputBitDepth",       &gConfig_disparity[4].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"4winWidth",              &gConfig_disparity[4].winWidth            , INT_8 , SINGLE},
        {(char* )"4winHeight",             &gConfig_disparity[4].winHeight           , INT_8 , SINGLE},
        {(char* )"4numDisparities",        &gConfig_disparity[4].numDisparities      , INT_16 , SINGLE},
        {(char* )"4disparityStep",         &gConfig_disparity[4].disparityStep       , INT_8 , SINGLE},
        {(char* )"4searchDir",             &gConfig_disparity[4].searchDir           , INT_8 , SINGLE},
        {(char* )"4outputCostType",        &gConfig_disparity[4].outputCostType      , INT_8 , SINGLE},
        
        {(char* )"5inImageLeft",           &gConfig_disparity[5].inImageLeft         , STRING, SINGLE},
        {(char* )"5inImageRight",          &gConfig_disparity[5].inImageRight        , STRING, SINGLE},
        {(char* )"5srcImageWidth",         &gConfig_disparity[5].srcImageWidth       , INT_32, SINGLE},
        {(char* )"5srcImageHeight",        &gConfig_disparity[5].srcImageHeight      , INT_32, SINGLE},
        {(char* )"5srcImagePitchL",        &gConfig_disparity[5].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"5srcImagePitchR",        &gConfig_disparity[5].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"5outImage",              &gConfig_disparity[5].outImage            , STRING, SINGLE},
        {(char* )"5dstImagePitch",         &gConfig_disparity[5].dstImagePitch       , INT_32, SINGLE},
        {(char* )"5pattern",               &gConfig_disparity[5].pattern             , INT_8 , SINGLE},
        {(char* )"5inputBitDepth",       &gConfig_disparity[5].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"5winWidth",              &gConfig_disparity[5].winWidth            , INT_8 , SINGLE},
        {(char* )"5winHeight",             &gConfig_disparity[5].winHeight           , INT_8 , SINGLE},
        {(char* )"5numDisparities",        &gConfig_disparity[5].numDisparities      , INT_16 , SINGLE},
        {(char* )"5disparityStep",         &gConfig_disparity[5].disparityStep       , INT_8 , SINGLE},
        {(char* )"5searchDir",             &gConfig_disparity[5].searchDir           , INT_8 , SINGLE},
        {(char* )"5outputCostType",        &gConfig_disparity[5].outputCostType      , INT_8 , SINGLE},
        
        {(char* )"6inImageLeft",           &gConfig_disparity[6].inImageLeft         , STRING, SINGLE},
        {(char* )"6inImageRight",          &gConfig_disparity[6].inImageRight        , STRING, SINGLE},
        {(char* )"6srcImageWidth",         &gConfig_disparity[6].srcImageWidth       , INT_32, SINGLE},
        {(char* )"6srcImageHeight",        &gConfig_disparity[6].srcImageHeight      , INT_32, SINGLE},
        {(char* )"6srcImagePitchL",        &gConfig_disparity[6].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"6srcImagePitchR",        &gConfig_disparity[6].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"6outImage",              &gConfig_disparity[6].outImage            , STRING, SINGLE},
        {(char* )"6dstImagePitch",         &gConfig_disparity[6].dstImagePitch       , INT_32, SINGLE},
        {(char* )"6pattern",               &gConfig_disparity[6].pattern             , INT_8 , SINGLE},
        {(char* )"6inputBitDepth",       &gConfig_disparity[6].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"6winWidth",              &gConfig_disparity[6].winWidth            , INT_8 , SINGLE},
        {(char* )"6winHeight",             &gConfig_disparity[6].winHeight           , INT_8 , SINGLE},
        {(char* )"6numDisparities",        &gConfig_disparity[6].numDisparities      , INT_16 , SINGLE},
        {(char* )"6disparityStep",         &gConfig_disparity[6].disparityStep       , INT_8 , SINGLE},
        {(char* )"6searchDir",             &gConfig_disparity[6].searchDir           , INT_8 , SINGLE},
        {(char* )"6outputCostType",        &gConfig_disparity[6].outputCostType      , INT_8 , SINGLE},
        
        {(char* )"7inImageLeft",           &gConfig_disparity[7].inImageLeft         , STRING, SINGLE},
        {(char* )"7inImageRight",          &gConfig_disparity[7].inImageRight        , STRING, SINGLE},
        {(char* )"7srcImageWidth",         &gConfig_disparity[7].srcImageWidth       , INT_32, SINGLE},
        {(char* )"7srcImageHeight",        &gConfig_disparity[7].srcImageHeight      , INT_32, SINGLE},
        {(char* )"7srcImagePitchL",        &gConfig_disparity[7].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"7srcImagePitchR",        &gConfig_disparity[7].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"7outImage",              &gConfig_disparity[7].outImage            , STRING, SINGLE},
        {(char* )"7dstImagePitch",         &gConfig_disparity[7].dstImagePitch       , INT_32, SINGLE},
        {(char* )"7pattern",               &gConfig_disparity[7].pattern             , INT_8 , SINGLE},
        {(char* )"7inputBitDepth",       &gConfig_disparity[7].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"7winWidth",              &gConfig_disparity[7].winWidth            , INT_8 , SINGLE},
        {(char* )"7winHeight",             &gConfig_disparity[7].winHeight           , INT_8 , SINGLE},
        {(char* )"7numDisparities",        &gConfig_disparity[7].numDisparities      , INT_16 , SINGLE},
        {(char* )"7disparityStep",         &gConfig_disparity[7].disparityStep       , INT_8 , SINGLE},
        {(char* )"7searchDir",             &gConfig_disparity[7].searchDir           , INT_8 , SINGLE},
        {(char* )"7outputCostType",        &gConfig_disparity[7].outputCostType      , INT_8 , SINGLE},

        {(char* )"8inImageLeft",           &gConfig_disparity[8].inImageLeft         , STRING, SINGLE},
        {(char* )"8inImageRight",          &gConfig_disparity[8].inImageRight        , STRING, SINGLE},
        {(char* )"8srcImageWidth",         &gConfig_disparity[8].srcImageWidth       , INT_32, SINGLE},
        {(char* )"8srcImageHeight",        &gConfig_disparity[8].srcImageHeight      , INT_32, SINGLE},
        {(char* )"8srcImagePitchL",        &gConfig_disparity[8].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"8srcImagePitchR",        &gConfig_disparity[8].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"8outImage",              &gConfig_disparity[8].outImage            , STRING, SINGLE},
        {(char* )"8dstImagePitch",         &gConfig_disparity[8].dstImagePitch       , INT_32, SINGLE},
        {(char* )"8pattern",               &gConfig_disparity[8].pattern             , INT_8 , SINGLE},
        {(char* )"8inputBitDepth",       &gConfig_disparity[8].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"8winWidth",              &gConfig_disparity[8].winWidth            , INT_8 , SINGLE},
        {(char* )"8winHeight",             &gConfig_disparity[8].winHeight           , INT_8 , SINGLE},
        {(char* )"8numDisparities",        &gConfig_disparity[8].numDisparities      , INT_16 , SINGLE},
        {(char* )"8disparityStep",         &gConfig_disparity[8].disparityStep       , INT_8 , SINGLE},
        {(char* )"8searchDir",             &gConfig_disparity[8].searchDir           , INT_8 , SINGLE},
        {(char* )"8outputCostType",        &gConfig_disparity[8].outputCostType      , INT_8 , SINGLE},

        {(char* )"9inImageLeft",           &gConfig_disparity[9].inImageLeft         , STRING, SINGLE},
        {(char* )"9inImageRight",          &gConfig_disparity[9].inImageRight        , STRING, SINGLE},
        {(char* )"9srcImageWidth",         &gConfig_disparity[9].srcImageWidth       , INT_32, SINGLE},
        {(char* )"9srcImageHeight",        &gConfig_disparity[9].srcImageHeight      , INT_32, SINGLE},
        {(char* )"9srcImagePitchL",        &gConfig_disparity[9].srcImagePitchL      , INT_32, SINGLE},
        {(char* )"9srcImagePitchR",        &gConfig_disparity[9].srcImagePitchR      , INT_32, SINGLE},

        {(char* )"9outImage",              &gConfig_disparity[9].outImage            , STRING, SINGLE},
        {(char* )"9dstImagePitch",         &gConfig_disparity[9].dstImagePitch       , INT_32, SINGLE},
        {(char* )"9pattern",               &gConfig_disparity[9].pattern             , INT_8 , SINGLE},
        {(char* )"9inputBitDepth",       &gConfig_disparity[9].inputBitDepth     , INT_8 , SINGLE},
        {(char* )"9winWidth",              &gConfig_disparity[9].winWidth            , INT_8 , SINGLE},
        {(char* )"9winHeight",             &gConfig_disparity[9].winHeight           , INT_8 , SINGLE},
        {(char* )"9numDisparities",        &gConfig_disparity[9].numDisparities      , INT_16 , SINGLE},
        {(char* )"9disparityStep",         &gConfig_disparity[9].disparityStep       , INT_8 , SINGLE},
        {(char* )"9searchDir",             &gConfig_disparity[9].searchDir           , INT_8 , SINGLE},
        {(char* )"9outputCostType",        &gConfig_disparity[9].outputCostType      , INT_8 , SINGLE},

} ;
