/* =============================================================================
 *   Copyright (c) Texas Instruments Incorporated 2014
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/**
 *  \file      pmhal_prcm_modinc.h
 *
 *  \brief     Contains the list of modules to be included for compilation
 *
 *  \warning   This file is auto generated. So avoid manual changes.
 *              If manual changes are required the implications of the
 *              change in this and other auto generated files has to be
 *              completely understood.
 */

#ifndef PMHAL_PRCM_MODINC_H_
#define PMHAL_PRCM_MODINC_H_

/* ========================================================================== */
/*                                Include Files                               */
/* ========================================================================== */

/* None */

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================== */
/*                             Macros and Typedefs                            */
/* ========================================================================== */

/**
 * \brief Comment off the (#defined) modules which you do not want to include
 */
#define BUILDCFG_PMHAL_PRCM_MOD_ATL
#define BUILDCFG_PMHAL_PRCM_MOD_DUMMY_MODULE4
#define BUILDCFG_PMHAL_PRCM_MOD_DUMMY_MODULE1
#define BUILDCFG_PMHAL_PRCM_MOD_DUMMY_MODULE2
#define BUILDCFG_PMHAL_PRCM_MOD_DUMMY_MODULE3
#define BUILDCFG_PMHAL_PRCM_MOD_IO_SRCOMP_CORE
#define BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_CORE
#define BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_DSPEVE
#define BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_GPU
#define BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_IVAHD
#define BUILDCFG_PMHAL_PRCM_MOD_SMARTREFLEX_MPU
#define BUILDCFG_PMHAL_PRCM_MOD_USB_PHY1_ALWAYS_ON
#define BUILDCFG_PMHAL_PRCM_MOD_USB_PHY2_ALWAYS_ON
#define BUILDCFG_PMHAL_PRCM_MOD_USB_PHY3_ALWAYS_ON
#define BUILDCFG_PMHAL_PRCM_MOD_EFUSE_CTRL_CUST
#define BUILDCFG_PMHAL_PRCM_MOD_DMA_SYSTEM
#define BUILDCFG_PMHAL_PRCM_MOD_DSP1

#define BUILDCFG_PMHAL_PRCM_MOD_DSP2

#define BUILDCFG_PMHAL_PRCM_MOD_BB2D
#define BUILDCFG_PMHAL_PRCM_MOD_DSS
#define BUILDCFG_PMHAL_PRCM_MOD_SDVENC
#define BUILDCFG_PMHAL_PRCM_MOD_DLL
#define BUILDCFG_PMHAL_PRCM_MOD_DMM
#define BUILDCFG_PMHAL_PRCM_MOD_EMIF1
#define BUILDCFG_PMHAL_PRCM_MOD_EMIF2
#define BUILDCFG_PMHAL_PRCM_MOD_EMIF_OCP_FW

#define BUILDCFG_PMHAL_PRCM_MOD_EVE1
#define BUILDCFG_PMHAL_PRCM_MOD_EVE2
#define BUILDCFG_PMHAL_PRCM_MOD_EVE3
#define BUILDCFG_PMHAL_PRCM_MOD_EVE4

#define BUILDCFG_PMHAL_PRCM_MOD_CPGMAC
#define BUILDCFG_PMHAL_PRCM_MOD_GPU
#define BUILDCFG_PMHAL_PRCM_MOD_I2C5
#define BUILDCFG_PMHAL_PRCM_MOD_MCASP1
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER5
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER6
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER7
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER8
#define BUILDCFG_PMHAL_PRCM_MOD_UART6
#define BUILDCFG_PMHAL_PRCM_MOD_IPU1
#define BUILDCFG_PMHAL_PRCM_MOD_IPU2
#define BUILDCFG_PMHAL_PRCM_MOD_IVA
#define BUILDCFG_PMHAL_PRCM_MOD_SL2
#define BUILDCFG_PMHAL_PRCM_MOD_IEEE1500_2_OCP
#define BUILDCFG_PMHAL_PRCM_MOD_MMC1
#define BUILDCFG_PMHAL_PRCM_MOD_MMC2
#define BUILDCFG_PMHAL_PRCM_MOD_MLB_SS
#define BUILDCFG_PMHAL_PRCM_MOD_SATA
#define BUILDCFG_PMHAL_PRCM_MOD_OCP2SCP1
#define BUILDCFG_PMHAL_PRCM_MOD_OCP2SCP3
#define BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS1
#define BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS2
#define BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS3
#define BUILDCFG_PMHAL_PRCM_MOD_USB_OTG_SS4
#define BUILDCFG_PMHAL_PRCM_MOD_CTRL_MODULE_BANDGAP
#define BUILDCFG_PMHAL_PRCM_MOD_DLL_AGING
#define BUILDCFG_PMHAL_PRCM_MOD_L3_INSTR
#define BUILDCFG_PMHAL_PRCM_MOD_L3_MAIN_2
#define BUILDCFG_PMHAL_PRCM_MOD_OCP_WP_NOC
#define BUILDCFG_PMHAL_PRCM_MOD_GPMC
#define BUILDCFG_PMHAL_PRCM_MOD_L3_MAIN_1
#define BUILDCFG_PMHAL_PRCM_MOD_MMU_EDMA
#define BUILDCFG_PMHAL_PRCM_MOD_MMU_PCIESS
#define BUILDCFG_PMHAL_PRCM_MOD_OCMC_RAM1
#define BUILDCFG_PMHAL_PRCM_MOD_OCMC_RAM2
#define BUILDCFG_PMHAL_PRCM_MOD_OCMC_RAM3

#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_IVA2
#define BUILDCFG_PMHAL_PRCM_MOD_VCP1
#define BUILDCFG_PMHAL_PRCM_MOD_VCP2
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_CME
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_HDMI
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_ICM
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_SATA2
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_UNKNOWN4
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_UNKNOWN5
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_UNKNOWN6
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_VIDEOPLL1
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_VIDEOPLL2
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_VIDEOPLL3
#define BUILDCFG_PMHAL_PRCM_MOD_TPCC
#define BUILDCFG_PMHAL_PRCM_MOD_TPTC1
#define BUILDCFG_PMHAL_PRCM_MOD_TPTC2
#define BUILDCFG_PMHAL_PRCM_MOD_L4_CFG
#define BUILDCFG_PMHAL_PRCM_MOD_OCP2SCP2
#define BUILDCFG_PMHAL_PRCM_MOD_SAR_ROM
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_SMARTREFLEX_RTC
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_SMARTREFLEX_SDRAM
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_SMARTREFLEX_WKUP
#define BUILDCFG_PMHAL_PRCM_MOD_SPINLOCK
#define BUILDCFG_PMHAL_PRCM_MOD_IO_DELAY_BLOCK
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX1
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX10
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX11
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX12
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX13
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX2
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX3
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX4
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX5
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX6
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX7
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX8
#define BUILDCFG_PMHAL_PRCM_MOD_MAILBOX9
#define BUILDCFG_PMHAL_PRCM_MOD_I2C1
#define BUILDCFG_PMHAL_PRCM_MOD_I2C2
#define BUILDCFG_PMHAL_PRCM_MOD_I2C3
#define BUILDCFG_PMHAL_PRCM_MOD_I2C4
#define BUILDCFG_PMHAL_PRCM_MOD_L4_PER1
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER10
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER11
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER2
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER3
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER4
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER9
#define BUILDCFG_PMHAL_PRCM_MOD_ELM
#define BUILDCFG_PMHAL_PRCM_MOD_HDQ1W
#define BUILDCFG_PMHAL_PRCM_MOD_MCSPI1
#define BUILDCFG_PMHAL_PRCM_MOD_MCSPI2
#define BUILDCFG_PMHAL_PRCM_MOD_MCSPI3
#define BUILDCFG_PMHAL_PRCM_MOD_MCSPI4
#define BUILDCFG_PMHAL_PRCM_MOD_UART1
#define BUILDCFG_PMHAL_PRCM_MOD_UART2
#define BUILDCFG_PMHAL_PRCM_MOD_UART3
#define BUILDCFG_PMHAL_PRCM_MOD_UART4
#define BUILDCFG_PMHAL_PRCM_MOD_UART5
#define BUILDCFG_PMHAL_PRCM_MOD_GPIO2
#define BUILDCFG_PMHAL_PRCM_MOD_GPIO3
#define BUILDCFG_PMHAL_PRCM_MOD_GPIO4
#define BUILDCFG_PMHAL_PRCM_MOD_GPIO5
#define BUILDCFG_PMHAL_PRCM_MOD_GPIO6
#define BUILDCFG_PMHAL_PRCM_MOD_GPIO7
#define BUILDCFG_PMHAL_PRCM_MOD_GPIO8
#define BUILDCFG_PMHAL_PRCM_MOD_MMC3
#define BUILDCFG_PMHAL_PRCM_MOD_MMC4
#define BUILDCFG_PMHAL_PRCM_MOD_DCAN2
#define BUILDCFG_PMHAL_PRCM_MOD_L4_PER2
#define BUILDCFG_PMHAL_PRCM_MOD_UART7
#define BUILDCFG_PMHAL_PRCM_MOD_UART8
#define BUILDCFG_PMHAL_PRCM_MOD_UART9
#define BUILDCFG_PMHAL_PRCM_MOD_PRUSS1
#define BUILDCFG_PMHAL_PRCM_MOD_PRUSS2
#define BUILDCFG_PMHAL_PRCM_MOD_MCASP2
#define BUILDCFG_PMHAL_PRCM_MOD_MCASP3
#define BUILDCFG_PMHAL_PRCM_MOD_MCASP4
#define BUILDCFG_PMHAL_PRCM_MOD_MCASP5
#define BUILDCFG_PMHAL_PRCM_MOD_MCASP6
#define BUILDCFG_PMHAL_PRCM_MOD_MCASP7
#define BUILDCFG_PMHAL_PRCM_MOD_MCASP8
#define BUILDCFG_PMHAL_PRCM_MOD_PWMSS1
#define BUILDCFG_PMHAL_PRCM_MOD_PWMSS2
#define BUILDCFG_PMHAL_PRCM_MOD_PWMSS3
#define BUILDCFG_PMHAL_PRCM_MOD_QSPI
#define BUILDCFG_PMHAL_PRCM_MOD_L4_PER3
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER13
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER14
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER15
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER16
#define BUILDCFG_PMHAL_PRCM_MOD_AES1
#define BUILDCFG_PMHAL_PRCM_MOD_AES2
#define BUILDCFG_PMHAL_PRCM_MOD_DES3DES
#define BUILDCFG_PMHAL_PRCM_MOD_DMA_CRYPTO
#define BUILDCFG_PMHAL_PRCM_MOD_FPKA
#define BUILDCFG_PMHAL_PRCM_MOD_RNG
#define BUILDCFG_PMHAL_PRCM_MOD_SHA2MD51
#define BUILDCFG_PMHAL_PRCM_MOD_SHA2MD52
#define BUILDCFG_PMHAL_PRCM_MOD_MPU
#define BUILDCFG_PMHAL_PRCM_MOD_MPU_MPU_DBG
#define BUILDCFG_PMHAL_PRCM_MOD_PCIESS1
#define BUILDCFG_PMHAL_PRCM_MOD_PCIESS2
#define BUILDCFG_PMHAL_PRCM_MOD_RTCSS

#define BUILDCFG_PMHAL_PRCM_MOD_LVDSRX
#define BUILDCFG_PMHAL_PRCM_MOD_VIP1
#define BUILDCFG_PMHAL_PRCM_MOD_VIP2
#define BUILDCFG_PMHAL_PRCM_MOD_VIP3
#define BUILDCFG_PMHAL_PRCM_MOD_VPE
#define BUILDCFG_PMHAL_PRCM_MOD_DEBUG_LOGIC
#define BUILDCFG_PMHAL_PRCM_MOD_MPU_EMU_DBG
#define BUILDCFG_PMHAL_PRCM_MOD_ADC
#define BUILDCFG_PMHAL_PRCM_MOD_COUNTER_32K
#define BUILDCFG_PMHAL_PRCM_MOD_CTRL_MODULE_WKUP
#define BUILDCFG_PMHAL_PRCM_MOD_DCAN1
#define BUILDCFG_PMHAL_PRCM_MOD_GPIO1
#define BUILDCFG_PMHAL_PRCM_MOD_IO_SRCOMP_WKUP
#define BUILDCFG_PMHAL_PRCM_MOD_KBD
#define BUILDCFG_PMHAL_PRCM_MOD_L4_WKUP
#define BUILDCFG_PMHAL_PRCM_MOD_SAR_RAM
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_SAFETY1
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_SAFETY2
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_SAFETY3
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_SAFETY4
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_UNKNOWN2
#define BUILDCFG_PMHAL_PRCM_MOD_SPARE_UNKNOWN3
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER1
#define BUILDCFG_PMHAL_PRCM_MOD_TIMER12
#define BUILDCFG_PMHAL_PRCM_MOD_UART10
#define BUILDCFG_PMHAL_PRCM_MOD_WD_TIMER1
#define BUILDCFG_PMHAL_PRCM_MOD_WD_TIMER2
#define BUILDCFG_PMHAL_PRCM_MOD_CAL
#define BUILDCFG_PMHAL_PRCM_MOD_I2C6
#define BUILDCFG_PMHAL_PRCM_MOD_OCMC_ROM

/* ========================================================================== */
/*                            Structures and Enums                            */
/* ========================================================================== */

/* None */

/* ========================================================================== */
/*                            Global Variables                                */
/* ========================================================================== */

/* None */

/* ========================================================================== */
/*                            Function Declarations                           */
/* ========================================================================== */

/* None */

#ifdef __cplusplus
}
#endif

#endif /* PMHAL_PRCM_MODINC_H_ */

