
/* ============================================================================
 *
 *            TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION
 *
 *  Property of Texas Instruments
 *  For Unrestricted Internal Use Only
 *  Unauthorized reproduction and/or distribution is strictly prohibited.
 *  This product is protected under copyright law and trade secret law
 *  as an unpublished work.
 *  Created 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved.
 *
 */

/**
 *  @Component:   MAILBOX
 *
 *  @Filename:    mailbox_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
 *//* ====================================================================== */

#ifndef __MAILBOX_CRED_H
#define __MAILBOX_CRED_H

#ifdef __cplusplus
extern "C"
{
#endif

/*
 * Instance MAILBOX of component MAILBOX mapped in EDEN at address 0x480C8000
 */

 /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
 *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

/*
 *  List of Register arrays for component MAILBOX
 *
 */


/*
 *  List of bundle arrays for component MAILBOX
 *
 */

/*
 *  List of bundles for component MAILBOX
 *
 */


/*
 * List of registers for component MAILBOX
 *
 */

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MAILBOX__DUMMY_REG__1
 *
 * @BRIEF        this cred will not be used 
 *
 *//*------------------------------------------------------------------------ */
#define MAILBOX__DUMMY_REG__1                              0x0ul


/*
 * List of register bitfields for component MAILBOX
 *
 */
 
/*-------------------------------------------------------------------------*//**
 * @DEFINITION   MAILBOX__DUMMY_REG__1__DUMMY_BITS   
 *
 * @BRIEF        this cred will not be used - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define MAILBOX__DUMMY_REG__1__DUMMY_BITS             BITFIELD(31, 0)
#define MAILBOX__DUMMY_REG__1__DUMMY_BITS__POS        0


/*
 * List of register bitfields values for component MAILBOX
 *
 */


#ifdef __cplusplus
}
#endif
#endif  /* __MAILBOX_CRED_H */
 
