#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
MK_NOGENDEPS := $(filter clean,$(MAKECMDGOALS))
override PKGDIR = ti/sdo/ipc
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/utils.js:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/utils.js
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xdc.tci:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xdc.tci
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/template.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/template.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/om2.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/om2.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xmlgen.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xmlgen.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xmlgen2.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/xmlgen2.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/Warnings.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/Warnings.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/IPackage.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/IPackage.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/package.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/package.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/services/global/Clock.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/services/global/Clock.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/services/global/Trace.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/services/global/Trace.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/bld.js:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/bld.js
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/BuildEnvironment.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/PackageContents.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/PackageContents.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/_gen.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/_gen.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Library.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Library.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Executable.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Executable.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Repository.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Repository.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Configuration.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Configuration.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Script.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Script.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Manifest.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Manifest.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Utils.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/Utils.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget2.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget2.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget3.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITarget3.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITargetFilter.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/ITargetFilter.xs
/datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/package.xs:
package.mak: /datalocal1/ti_components/os_tools/linux/xdctools_3_31_02_38_core/packages/xdc/bld/package.xs
/datalocal1/ti_components/os_tools/ipc_3_40_00_06/ipc-bios.bld:
package.mak: /datalocal1/ti_components/os_tools/ipc_3_40_00_06/ipc-bios.bld
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/ITarget.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/ITarget.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/C28_large.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/C28_large.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/C28_float.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/C28_float.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/package.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/package.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/IArm.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/IArm.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/package.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/package.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/ITarget.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/ITarget.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/package.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/package.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/IARP32.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/IARP32.xs
/datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/package.xs:
package.mak: /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/package.xs
package.mak: package.bld
package.mak: Build.xs
endif

ti.targets.arm.elf.M4.rootDir ?= /datalocal1/ti_components/cg_tools/linux/ti-cgt-arm_5.2.5
ti.targets.arm.elf.packageBase ?= /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arm/elf/
ti.targets.elf.C66.rootDir ?= /datalocal1/ti_components/cg_tools/linux/c6000_7_4_2
ti.targets.elf.packageBase ?= /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/elf/
ti.targets.arp32.elf.ARP32.rootDir ?= /datalocal1/ti_components/cg_tools/linux/arp32_1_0_6
ti.targets.arp32.elf.packageBase ?= /datalocal1/ti_components/os_tools/bios_6_42_02_29/packages/ti/targets/arp32/elf/
.PRECIOUS: $(XDCCFGDIR)/%.oem4
.PHONY: all,em4 .dlls,em4 .executables,em4 test,em4
all,em4: .executables,em4
.executables,em4: .libraries,em4
.executables,em4: .dlls,em4
.dlls,em4: .libraries,em4
.libraries,em4: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,em4
	@$(ECHO) xdc .executables,em4
	@$(ECHO) xdc .libraries,em4
	@$(ECHO) xdc .dlls,em4

.PRECIOUS: $(XDCCFGDIR)/%.oe66
.PHONY: all,e66 .dlls,e66 .executables,e66 test,e66
all,e66: .executables,e66
.executables,e66: .libraries,e66
.executables,e66: .dlls,e66
.dlls,e66: .libraries,e66
.libraries,e66: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,e66
	@$(ECHO) xdc .executables,e66
	@$(ECHO) xdc .libraries,e66
	@$(ECHO) xdc .dlls,e66

.PRECIOUS: $(XDCCFGDIR)/%.oearp32
.PHONY: all,earp32 .dlls,earp32 .executables,earp32 test,earp32
all,earp32: .executables,earp32
.executables,earp32: .libraries,earp32
.executables,earp32: .dlls,earp32
.dlls,earp32: .libraries,earp32
.libraries,earp32: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,earp32
	@$(ECHO) xdc .executables,earp32
	@$(ECHO) xdc .libraries,earp32
	@$(ECHO) xdc .dlls,earp32


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sdo.ipc.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.ipc" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifeq (,$(MK_NOGENDEPS))
-include package/package.cfg.dep
endif

package/package.cfg.xdc.inc: .interfaces $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.ipc $@

.dlls,em4 .dlls: instrumented.pem4

-include package/cfg/instrumented_pem4.mak
-include package/cfg/instrumented_pem4.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/instrumented_pem4.dep
endif
instrumented.pem4: package/cfg/instrumented_pem4.xdl
	@$(RM) $@
	@$(TOUCH) $@


ifeq (,$(wildcard .libraries,em4))
instrumented.pem4 package/cfg/instrumented_pem4.c: .libraries,em4
endif

package/cfg/instrumented_pem4.c package/cfg/instrumented_pem4.h package/cfg/instrumented_pem4.xdl: override _PROG_NAME := instrumented.pem4
package/cfg/instrumented_pem4.c: package/cfg/instrumented_pem4.cfg
package/cfg/instrumented_pem4.xdc.inc: package/cfg/instrumented_pem4.xdl
package/cfg/instrumented_pem4.xdl package/cfg/instrumented_pem4.c: .interfaces

clean:: clean,em4
	-$(RM) package/cfg/instrumented_pem4.cfg
	-$(RM) package/cfg/instrumented_pem4.dep
	-$(RM) package/cfg/instrumented_pem4.c
	-$(RM) package/cfg/instrumented_pem4.xdc.inc

clean,em4::
	-$(RM) instrumented.pem4
.dlls,em4 .dlls: nonInstrumented.pem4

-include package/cfg/nonInstrumented_pem4.mak
-include package/cfg/nonInstrumented_pem4.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/nonInstrumented_pem4.dep
endif
nonInstrumented.pem4: package/cfg/nonInstrumented_pem4.xdl
	@$(RM) $@
	@$(TOUCH) $@


ifeq (,$(wildcard .libraries,em4))
nonInstrumented.pem4 package/cfg/nonInstrumented_pem4.c: .libraries,em4
endif

package/cfg/nonInstrumented_pem4.c package/cfg/nonInstrumented_pem4.h package/cfg/nonInstrumented_pem4.xdl: override _PROG_NAME := nonInstrumented.pem4
package/cfg/nonInstrumented_pem4.c: package/cfg/nonInstrumented_pem4.cfg
package/cfg/nonInstrumented_pem4.xdc.inc: package/cfg/nonInstrumented_pem4.xdl
package/cfg/nonInstrumented_pem4.xdl package/cfg/nonInstrumented_pem4.c: .interfaces

clean:: clean,em4
	-$(RM) package/cfg/nonInstrumented_pem4.cfg
	-$(RM) package/cfg/nonInstrumented_pem4.dep
	-$(RM) package/cfg/nonInstrumented_pem4.c
	-$(RM) package/cfg/nonInstrumented_pem4.xdc.inc

clean,em4::
	-$(RM) nonInstrumented.pem4
.dlls,e66 .dlls: instrumented.pe66

-include package/cfg/instrumented_pe66.mak
-include package/cfg/instrumented_pe66.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/instrumented_pe66.dep
endif
instrumented.pe66: package/cfg/instrumented_pe66.xdl
	@$(RM) $@
	@$(TOUCH) $@


ifeq (,$(wildcard .libraries,e66))
instrumented.pe66 package/cfg/instrumented_pe66.c: .libraries,e66
endif

package/cfg/instrumented_pe66.c package/cfg/instrumented_pe66.h package/cfg/instrumented_pe66.xdl: override _PROG_NAME := instrumented.pe66
package/cfg/instrumented_pe66.c: package/cfg/instrumented_pe66.cfg
package/cfg/instrumented_pe66.xdc.inc: package/cfg/instrumented_pe66.xdl
package/cfg/instrumented_pe66.xdl package/cfg/instrumented_pe66.c: .interfaces

clean:: clean,e66
	-$(RM) package/cfg/instrumented_pe66.cfg
	-$(RM) package/cfg/instrumented_pe66.dep
	-$(RM) package/cfg/instrumented_pe66.c
	-$(RM) package/cfg/instrumented_pe66.xdc.inc

clean,e66::
	-$(RM) instrumented.pe66
.dlls,e66 .dlls: nonInstrumented.pe66

-include package/cfg/nonInstrumented_pe66.mak
-include package/cfg/nonInstrumented_pe66.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/nonInstrumented_pe66.dep
endif
nonInstrumented.pe66: package/cfg/nonInstrumented_pe66.xdl
	@$(RM) $@
	@$(TOUCH) $@


ifeq (,$(wildcard .libraries,e66))
nonInstrumented.pe66 package/cfg/nonInstrumented_pe66.c: .libraries,e66
endif

package/cfg/nonInstrumented_pe66.c package/cfg/nonInstrumented_pe66.h package/cfg/nonInstrumented_pe66.xdl: override _PROG_NAME := nonInstrumented.pe66
package/cfg/nonInstrumented_pe66.c: package/cfg/nonInstrumented_pe66.cfg
package/cfg/nonInstrumented_pe66.xdc.inc: package/cfg/nonInstrumented_pe66.xdl
package/cfg/nonInstrumented_pe66.xdl package/cfg/nonInstrumented_pe66.c: .interfaces

clean:: clean,e66
	-$(RM) package/cfg/nonInstrumented_pe66.cfg
	-$(RM) package/cfg/nonInstrumented_pe66.dep
	-$(RM) package/cfg/nonInstrumented_pe66.c
	-$(RM) package/cfg/nonInstrumented_pe66.xdc.inc

clean,e66::
	-$(RM) nonInstrumented.pe66
.dlls,earp32 .dlls: instrumented.pearp32

-include package/cfg/instrumented_pearp32.mak
-include package/cfg/instrumented_pearp32.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/instrumented_pearp32.dep
endif
instrumented.pearp32: package/cfg/instrumented_pearp32.xdl
	@$(RM) $@
	@$(TOUCH) $@


ifeq (,$(wildcard .libraries,earp32))
instrumented.pearp32 package/cfg/instrumented_pearp32.c: .libraries,earp32
endif

package/cfg/instrumented_pearp32.c package/cfg/instrumented_pearp32.h package/cfg/instrumented_pearp32.xdl: override _PROG_NAME := instrumented.pearp32
package/cfg/instrumented_pearp32.c: package/cfg/instrumented_pearp32.cfg
package/cfg/instrumented_pearp32.xdc.inc: package/cfg/instrumented_pearp32.xdl
package/cfg/instrumented_pearp32.xdl package/cfg/instrumented_pearp32.c: .interfaces

clean:: clean,earp32
	-$(RM) package/cfg/instrumented_pearp32.cfg
	-$(RM) package/cfg/instrumented_pearp32.dep
	-$(RM) package/cfg/instrumented_pearp32.c
	-$(RM) package/cfg/instrumented_pearp32.xdc.inc

clean,earp32::
	-$(RM) instrumented.pearp32
.dlls,earp32 .dlls: nonInstrumented.pearp32

-include package/cfg/nonInstrumented_pearp32.mak
-include package/cfg/nonInstrumented_pearp32.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/nonInstrumented_pearp32.dep
endif
nonInstrumented.pearp32: package/cfg/nonInstrumented_pearp32.xdl
	@$(RM) $@
	@$(TOUCH) $@


ifeq (,$(wildcard .libraries,earp32))
nonInstrumented.pearp32 package/cfg/nonInstrumented_pearp32.c: .libraries,earp32
endif

package/cfg/nonInstrumented_pearp32.c package/cfg/nonInstrumented_pearp32.h package/cfg/nonInstrumented_pearp32.xdl: override _PROG_NAME := nonInstrumented.pearp32
package/cfg/nonInstrumented_pearp32.c: package/cfg/nonInstrumented_pearp32.cfg
package/cfg/nonInstrumented_pearp32.xdc.inc: package/cfg/nonInstrumented_pearp32.xdl
package/cfg/nonInstrumented_pearp32.xdl package/cfg/nonInstrumented_pearp32.c: .interfaces

clean:: clean,earp32
	-$(RM) package/cfg/nonInstrumented_pearp32.cfg
	-$(RM) package/cfg/nonInstrumented_pearp32.dep
	-$(RM) package/cfg/nonInstrumented_pearp32.c
	-$(RM) package/cfg/nonInstrumented_pearp32.xdc.inc

clean,earp32::
	-$(RM) nonInstrumented.pearp32
.dlls,em4 .dlls: smpInstrumented.pem4

-include package/cfg/smpInstrumented_pem4.mak
-include package/cfg/smpInstrumented_pem4.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/smpInstrumented_pem4.dep
endif
smpInstrumented.pem4: package/cfg/smpInstrumented_pem4.xdl
	@$(RM) $@
	@$(TOUCH) $@


ifeq (,$(wildcard .libraries,em4))
smpInstrumented.pem4 package/cfg/smpInstrumented_pem4.c: .libraries,em4
endif

package/cfg/smpInstrumented_pem4.c package/cfg/smpInstrumented_pem4.h package/cfg/smpInstrumented_pem4.xdl: override _PROG_NAME := smpInstrumented.pem4
package/cfg/smpInstrumented_pem4.c: package/cfg/smpInstrumented_pem4.cfg
package/cfg/smpInstrumented_pem4.xdc.inc: package/cfg/smpInstrumented_pem4.xdl
package/cfg/smpInstrumented_pem4.xdl package/cfg/smpInstrumented_pem4.c: .interfaces

clean:: clean,em4
	-$(RM) package/cfg/smpInstrumented_pem4.cfg
	-$(RM) package/cfg/smpInstrumented_pem4.dep
	-$(RM) package/cfg/smpInstrumented_pem4.c
	-$(RM) package/cfg/smpInstrumented_pem4.xdc.inc

clean,em4::
	-$(RM) smpInstrumented.pem4
.dlls,em4 .dlls: smpNonInstrumented.pem4

-include package/cfg/smpNonInstrumented_pem4.mak
-include package/cfg/smpNonInstrumented_pem4.cfg.mak
ifeq (,$(MK_NOGENDEPS))
-include package/cfg/smpNonInstrumented_pem4.dep
endif
smpNonInstrumented.pem4: package/cfg/smpNonInstrumented_pem4.xdl
	@$(RM) $@
	@$(TOUCH) $@


ifeq (,$(wildcard .libraries,em4))
smpNonInstrumented.pem4 package/cfg/smpNonInstrumented_pem4.c: .libraries,em4
endif

package/cfg/smpNonInstrumented_pem4.c package/cfg/smpNonInstrumented_pem4.h package/cfg/smpNonInstrumented_pem4.xdl: override _PROG_NAME := smpNonInstrumented.pem4
package/cfg/smpNonInstrumented_pem4.c: package/cfg/smpNonInstrumented_pem4.cfg
package/cfg/smpNonInstrumented_pem4.xdc.inc: package/cfg/smpNonInstrumented_pem4.xdl
package/cfg/smpNonInstrumented_pem4.xdl package/cfg/smpNonInstrumented_pem4.c: .interfaces

clean:: clean,em4
	-$(RM) package/cfg/smpNonInstrumented_pem4.cfg
	-$(RM) package/cfg/smpNonInstrumented_pem4.dep
	-$(RM) package/cfg/smpNonInstrumented_pem4.c
	-$(RM) package/cfg/smpNonInstrumented_pem4.xdc.inc

clean,em4::
	-$(RM) smpNonInstrumented.pem4
test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
instrumented_pem4.oem4,copy : package/cfg/instrumented_pem4.oem4
instrumented_pem4.sem4,copy : package/cfg/instrumented_pem4.sem4
nonInstrumented_pem4.oem4,copy : package/cfg/nonInstrumented_pem4.oem4
nonInstrumented_pem4.sem4,copy : package/cfg/nonInstrumented_pem4.sem4
instrumented_pe66.oe66,copy : package/cfg/instrumented_pe66.oe66
instrumented_pe66.se66,copy : package/cfg/instrumented_pe66.se66
nonInstrumented_pe66.oe66,copy : package/cfg/nonInstrumented_pe66.oe66
nonInstrumented_pe66.se66,copy : package/cfg/nonInstrumented_pe66.se66
instrumented_pearp32.oearp32,copy : package/cfg/instrumented_pearp32.oearp32
instrumented_pearp32.searp32,copy : package/cfg/instrumented_pearp32.searp32
nonInstrumented_pearp32.oearp32,copy : package/cfg/nonInstrumented_pearp32.oearp32
nonInstrumented_pearp32.searp32,copy : package/cfg/nonInstrumented_pearp32.searp32
smpInstrumented_pem4.oem4,copy : package/cfg/smpInstrumented_pem4.oem4
smpInstrumented_pem4.sem4,copy : package/cfg/smpInstrumented_pem4.sem4
smpNonInstrumented_pem4.oem4,copy : package/cfg/smpNonInstrumented_pem4.oem4
smpNonInstrumented_pem4.sem4,copy : package/cfg/smpNonInstrumented_pem4.sem4

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg $(XDCROOT)/packages/xdc/cfg/Main.xs | .interfaces
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_ipc
ifeq (,$(MK_NOGENDEPS))
-include package/rel/ti_sdo_ipc.tar.gz.dep
endif
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: package/package.bld.xml
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: package/build.cfg
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: package/package.xdc.inc
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: package.bld
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: linkcmd.xdt
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: _GateMP.h
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: _ListMP.h
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: _Notify.h
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: _MessageQ.h
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: _SharedRegion.h
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: _Ipc.h
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: Ipc.c
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: makefile.xdt
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: debugMakefile.xdt
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: makefile_gccArmLto.xdt
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: instrumented.cfg.xs
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: nonInstrumented.cfg.xs
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: instrumented.cfg
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: nonInstrumented.cfg
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: smpInstrumented.cfg
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: smpNonInstrumented.cfg
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: Notify.c
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: GateMP.c
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: MessageQ.c
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: SharedRegion.c
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: ListMP.c
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: lib/ipc/instrumented/ipc.aem4
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: lib/ipc/nonInstrumented/ipc.aem4
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: lib/ipc/instrumented/ipc.ae66
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: lib/ipc/nonInstrumented/ipc.ae66
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: lib/ipc/instrumented/ipc.aearp32
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: lib/ipc/nonInstrumented/ipc.aearp32
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: lib/smpipc/instrumented/ipc.aem4
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: lib/smpipc/nonInstrumented/ipc.aem4
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: package/package.cfg.xdc.inc
package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml: .force
	@$(MSG) generating external release references $@ ...
	$(XS) $(JSENV) -f $(XDCROOT)/packages/xdc/bld/rel.js $(MK_RELOPTS) . $@

ti_sdo_ipc.tar.gz: package/rel/ti_sdo_ipc.xdc.inc package/rel/ti_sdo_ipc/ti/sdo/ipc/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sdo_ipc.xdc.inc,package/rel/ti_sdo_ipc.tar.gz.dep)


release release,ti_sdo_ipc: all ti_sdo_ipc.tar.gz
clean:: .clean
	-$(RM) ti_sdo_ipc.tar.gz
	-$(RM) package/rel/ti_sdo_ipc.xdc.inc
	-$(RM) package/rel/ti_sdo_ipc.tar.gz.dep

clean:: .clean
	-$(RM) .libraries $(wildcard .libraries,*)
clean:: 
	-$(RM) .dlls $(wildcard .dlls,*)
#
# The following clean rule removes user specified
# generated files or directories.
#
	-$(RMDIR) lib/
	-$(RMDIR) lib/
	-$(RMDIR) custom/

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


