.bd B 3
.TH armlibinfo 1 "Jul 28, 2015" "TI Tools" "TI Code Generation Tools"
.SH NAME
armlibinfo - Library Information Archiver
.SH SYNOPSIS
.B armlibinfo
[
.I options
] [
.I file(s)
]
.SH DESCRIPTION
Builds an archive of information about available libraries.
This tool should be invoked via the shell (cl).  See the shell documentation for information on shell options.
.SH COPYRIGHT
.TP
Copyright (c) 2015, Texas Instruments, Inc.
