
/* ============================================================================
 *
 *            TEXAS INSTRUMENTS INCORPORATED PROPRIETARY INFORMATION
 *
 *  Property of Texas Instruments
 *  For Unrestricted Internal Use Only
 *  Unauthorized reproduction and/or distribution is strictly prohibited.
 *  This product is protected under copyright law and trade secret law
 *  as an unpublished work.
 *  Created 2008, (C) Copyright 2008 Texas Instruments.  All rights reserved.
 *
 */

/**
 *  @Component:   EVE_DMEM
 *
 *  @Filename:    eve_dmem_cred.h
 *
 *  @Description: Component description is not available
 *
 *  Generated by: Socrates CRED generator prototype
 *
 *//* ====================================================================== */

#ifndef __EVE_DMEM_CRED_H
#define __EVE_DMEM_CRED_H

#ifdef __cplusplus
extern "C"
{
#endif

/*
 * Instance DMEM of component EVE_DMEM mapped in EVE at address 0x20000
 * Instance WBUF of component EVE_DMEM mapped in EVE at address 0x40000
 */

 /*-------------------------------------------------------------------------*//**
 * @DEFINITION   BITFIELD
 *
 * @BRIEF        The bitfield must be defined according to register width
 *               of the component - 64/32/16/8
 *
 *//*------------------------------------------------------------------------ */
#undef BITFIELD
#define BITFIELD BITFIELD_32

/*
 *  List of Register arrays for component EVE_DMEM
 *
 */

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   EVE_DMEM__DMEM
 *
 * @BRIEF        T16 Data Memory 
 *
 *//*------------------------------------------------------------------------ */
#define EVE_DMEM__DMEM                                     0x0ul

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   EVE_DMEM__DMEM__ELSIZE
 *
 * @BRIEF        DMEM register array element size in Bytes
 *
 *//*------------------------------------------------------------------------ */
#define EVE_DMEM__DMEM__ELSIZE                             0x4ul

/*-------------------------------------------------------------------------*//**
 * @DEFINITION   EVE_DMEM__DMEM__NELEMS
 *
 * @BRIEF        DMEM register array number of elements
 *
 *//*------------------------------------------------------------------------ */
#define EVE_DMEM__DMEM__NELEMS                             8192


/*
 *  List of bundle arrays for component EVE_DMEM
 *
 */

/*
 *  List of bundles for component EVE_DMEM
 *
 */


/*
 * List of registers for component EVE_DMEM
 *
 */


/*
 * List of register bitfields for component EVE_DMEM
 *
 */
 
/*-------------------------------------------------------------------------*//**
 * @DEFINITION   EVE_DMEM__DMEM__MEMDATA   
 *
 * @BRIEF        Bitfield description is not available - (RW) 
 *
 *//*------------------------------------------------------------------------ */
#define EVE_DMEM__DMEM__MEMDATA                       BITFIELD(31, 0)
#define EVE_DMEM__DMEM__MEMDATA__POS                  0


/*
 * List of register bitfields values for component EVE_DMEM
 *
 */


#ifdef __cplusplus
}
#endif
#endif  /* __EVE_DMEM_CRED_H */
 
